/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import {
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const taggingAutocompleteRetrieve = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/tagging/autocomplete`, method: 'GET', signal
    },
      options);
    }
  



export const getTaggingAutocompleteRetrieveQueryKey = () => {
    return [
    `/api/tagging/autocomplete`
    ] as const;
    }

    
export const getTaggingAutocompleteRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof taggingAutocompleteRetrieve>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof taggingAutocompleteRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTaggingAutocompleteRetrieveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof taggingAutocompleteRetrieve>>> = ({ signal }) => taggingAutocompleteRetrieve(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof taggingAutocompleteRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type TaggingAutocompleteRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof taggingAutocompleteRetrieve>>>
export type TaggingAutocompleteRetrieveQueryError = unknown



export function createTaggingAutocompleteRetrieve<TData = Awaited<ReturnType<typeof taggingAutocompleteRetrieve>>, TError = unknown>(
  options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof taggingAutocompleteRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getTaggingAutocompleteRetrieveQueryOptions(options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



