/**
 * Generated by orval 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import { createMutation, createQuery } from "@tanstack/svelte-query";
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
} from "@tanstack/svelte-query";

import type {
  CommentList,
  CommentsList2Params,
  CommentsListParams,
  CommentsRepliesListParams,
  PaginatedCommentListList,
  PatchedCommentList,
} from "../f2z.schemas";

import { customInstance } from ".././mutator";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getCommentsListUrl = (params?: CommentsListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/comments/?${stringifiedParams}`
    : `/api/comments/`;
};

export const commentsList = async (
  params?: CommentsListParams,
  options?: Parameters<typeof customInstance>[1],
): Promise<PaginatedCommentListList> => {
  return customInstance<PaginatedCommentListList>(getCommentsListUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getCommentsListQueryKey = (params?: CommentsListParams) => {
  return [`/api/comments/`, ...(params ? [params] : [])] as const;
};

export const getCommentsListQueryOptions = <
  TData = Awaited<ReturnType<typeof commentsList>>,
  TError = unknown,
>(
  params?: CommentsListParams,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof commentsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCommentsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof commentsList>>> = ({
    signal,
  }) => commentsList(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof commentsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CommentsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof commentsList>>
>;
export type CommentsListQueryError = unknown;

export function createCommentsList<
  TData = Awaited<ReturnType<typeof commentsList>>,
  TError = unknown,
>(
  params?: CommentsListParams,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof commentsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCommentsListQueryOptions(params, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCommentsCreateUrl = () => {
  return `/api/comments/`;
};

export const commentsCreate = async (
  commentList: NonReadonly<CommentList>,
  options?: Parameters<typeof customInstance>[1],
): Promise<CommentList> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customInstance<CommentList>(getCommentsCreateUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(commentList),
  });
};

export const getCommentsCreateMutationKey = () => ["commentsCreate"] as const;

export const getCommentsCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof commentsCreate>>,
    TError,
    CommentsCreateMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof commentsCreate>>,
  TError,
  CommentsCreateMutationVariables,
  TContext
> => {
  const mutationKey = getCommentsCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof commentsCreate>>,
    CommentsCreateMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return commentsCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommentsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof commentsCreate>>
>;
export type CommentsCreateMutationBody = NonReadonly<CommentList>;
export type CommentsCreateMutationError = unknown;
export type CommentsCreateMutationVariables = {
  data: NonReadonly<CommentList>;
};

export const createCommentsCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof commentsCreate>>,
      TError,
      CommentsCreateMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof commentsCreate>>,
  TError,
  CommentsCreateMutationVariables,
  TContext
> => {
  return createMutation(getCommentsCreateMutationOptions(options));
};
export const getCommentsList2Url = (
  type: string,
  uuid: string,
  params?: CommentsList2Params,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/comments/${type}/${uuid}/?${stringifiedParams}`
    : `/api/comments/${type}/${uuid}/`;
};

/**
 * Comments under a content object identified by UUID and type
 */
export const commentsList2 = async (
  type: string,
  uuid: string,
  params?: CommentsList2Params,
  options?: Parameters<typeof customInstance>[1],
): Promise<PaginatedCommentListList> => {
  return customInstance<PaginatedCommentListList>(
    getCommentsList2Url(type, uuid, params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getCommentsList2QueryKey = (
  type: string,
  uuid: string,
  params?: CommentsList2Params,
) => {
  return [
    `/api/comments/${type}/${uuid}/`,
    ...(params ? [params] : []),
  ] as const;
};

export const getCommentsList2QueryOptions = <
  TData = Awaited<ReturnType<typeof commentsList2>>,
  TError = unknown,
>(
  type: string,
  uuid: string,
  params?: CommentsList2Params,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof commentsList2>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCommentsList2QueryKey(type, uuid, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof commentsList2>>> = ({
    signal,
  }) => commentsList2(type, uuid, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled:
      type !== null &&
      type !== undefined &&
      uuid !== null &&
      uuid !== undefined,
    ...queryOptions,
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof commentsList2>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CommentsList2QueryResult = NonNullable<
  Awaited<ReturnType<typeof commentsList2>>
>;
export type CommentsList2QueryError = unknown;

export function createCommentsList2<
  TData = Awaited<ReturnType<typeof commentsList2>>,
  TError = unknown,
>(
  type: string,
  uuid: string,
  params?: CommentsList2Params,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof commentsList2>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCommentsList2QueryOptions(
    type,
    uuid,
    params,
    options,
  );

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCommentsCreate2Url = (type: string, uuid: string) => {
  return `/api/comments/${type}/${uuid}/`;
};

/**
 * Comments under a content object identified by UUID and type
 */
export const commentsCreate2 = async (
  type: string,
  uuid: string,
  commentList: NonReadonly<CommentList>,
  options?: Parameters<typeof customInstance>[1],
): Promise<CommentList> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customInstance<CommentList>(getCommentsCreate2Url(type, uuid), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(commentList),
  });
};

export const getCommentsCreate2MutationKey = () => ["commentsCreate2"] as const;

export const getCommentsCreate2MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof commentsCreate2>>,
    TError,
    CommentsCreate2MutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof commentsCreate2>>,
  TError,
  CommentsCreate2MutationVariables,
  TContext
> => {
  const mutationKey = getCommentsCreate2MutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof commentsCreate2>>,
    CommentsCreate2MutationVariables
  > = (props) => {
    const { type, uuid, data } = props ?? {};

    return commentsCreate2(type, uuid, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommentsCreate2MutationResult = NonNullable<
  Awaited<ReturnType<typeof commentsCreate2>>
>;
export type CommentsCreate2MutationBody = NonReadonly<CommentList>;
export type CommentsCreate2MutationError = unknown;
export type CommentsCreate2MutationVariables = {
  type: string;
  uuid: string;
  data: NonReadonly<CommentList>;
};

export const createCommentsCreate2 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof commentsCreate2>>,
      TError,
      CommentsCreate2MutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof commentsCreate2>>,
  TError,
  CommentsCreate2MutationVariables,
  TContext
> => {
  return createMutation(getCommentsCreate2MutationOptions(options));
};
export const getCommentsRetrieveUrl = (uuid: string) => {
  return `/api/comments/${uuid}/`;
};

export const commentsRetrieve = async (
  uuid: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<CommentList> => {
  return customInstance<CommentList>(getCommentsRetrieveUrl(uuid), {
    ...options,
    method: "GET",
  });
};

export const getCommentsRetrieveQueryKey = (uuid: string) => {
  return [`/api/comments/${uuid}/`] as const;
};

export const getCommentsRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof commentsRetrieve>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof commentsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCommentsRetrieveQueryKey(uuid);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof commentsRetrieve>>
  > = ({ signal }) => commentsRetrieve(uuid, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: uuid !== null && uuid !== undefined,
    ...queryOptions,
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof commentsRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CommentsRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof commentsRetrieve>>
>;
export type CommentsRetrieveQueryError = unknown;

export function createCommentsRetrieve<
  TData = Awaited<ReturnType<typeof commentsRetrieve>>,
  TError = unknown,
>(
  uuid: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof commentsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCommentsRetrieveQueryOptions(uuid, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCommentsUpdateUrl = (uuid: string) => {
  return `/api/comments/${uuid}/`;
};

export const commentsUpdate = async (
  uuid: string,
  commentList: NonReadonly<CommentList>,
  options?: Parameters<typeof customInstance>[1],
): Promise<CommentList> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customInstance<CommentList>(getCommentsUpdateUrl(uuid), {
    ...options,
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(commentList),
  });
};

export const getCommentsUpdateMutationKey = () => ["commentsUpdate"] as const;

export const getCommentsUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof commentsUpdate>>,
    TError,
    CommentsUpdateMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof commentsUpdate>>,
  TError,
  CommentsUpdateMutationVariables,
  TContext
> => {
  const mutationKey = getCommentsUpdateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof commentsUpdate>>,
    CommentsUpdateMutationVariables
  > = (props) => {
    const { uuid, data } = props ?? {};

    return commentsUpdate(uuid, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommentsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof commentsUpdate>>
>;
export type CommentsUpdateMutationBody = NonReadonly<CommentList>;
export type CommentsUpdateMutationError = unknown;
export type CommentsUpdateMutationVariables = {
  uuid: string;
  data: NonReadonly<CommentList>;
};

export const createCommentsUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof commentsUpdate>>,
      TError,
      CommentsUpdateMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof commentsUpdate>>,
  TError,
  CommentsUpdateMutationVariables,
  TContext
> => {
  return createMutation(getCommentsUpdateMutationOptions(options));
};
export const getCommentsPartialUpdateUrl = (uuid: string) => {
  return `/api/comments/${uuid}/`;
};

export const commentsPartialUpdate = async (
  uuid: string,
  patchedCommentList?: NonReadonly<PatchedCommentList>,
  options?: Parameters<typeof customInstance>[1],
): Promise<CommentList> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customInstance<CommentList>(getCommentsPartialUpdateUrl(uuid), {
    ...options,
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(patchedCommentList),
  });
};

export const getCommentsPartialUpdateMutationKey = () =>
  ["commentsPartialUpdate"] as const;

export const getCommentsPartialUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof commentsPartialUpdate>>,
    TError,
    CommentsPartialUpdateMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof commentsPartialUpdate>>,
  TError,
  CommentsPartialUpdateMutationVariables,
  TContext
> => {
  const mutationKey = getCommentsPartialUpdateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof commentsPartialUpdate>>,
    CommentsPartialUpdateMutationVariables
  > = (props) => {
    const { uuid, data } = props ?? {};

    return commentsPartialUpdate(uuid, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommentsPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof commentsPartialUpdate>>
>;
export type CommentsPartialUpdateMutationBody =
  NonReadonly<PatchedCommentList> | undefined;
export type CommentsPartialUpdateMutationError = unknown;
export type CommentsPartialUpdateMutationVariables = {
  uuid: string;
  data?: NonReadonly<PatchedCommentList>;
};

export const createCommentsPartialUpdate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof commentsPartialUpdate>>,
      TError,
      CommentsPartialUpdateMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof commentsPartialUpdate>>,
  TError,
  CommentsPartialUpdateMutationVariables,
  TContext
> => {
  return createMutation(getCommentsPartialUpdateMutationOptions(options));
};
export const getCommentsDestroyUrl = (uuid: string) => {
  return `/api/comments/${uuid}/`;
};

export const commentsDestroy = async (
  uuid: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getCommentsDestroyUrl(uuid), {
    ...options,
    method: "DELETE",
  });
};

export const getCommentsDestroyMutationKey = () => ["commentsDestroy"] as const;

export const getCommentsDestroyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof commentsDestroy>>,
    TError,
    CommentsDestroyMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof commentsDestroy>>,
  TError,
  CommentsDestroyMutationVariables,
  TContext
> => {
  const mutationKey = getCommentsDestroyMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof commentsDestroy>>,
    CommentsDestroyMutationVariables
  > = (props) => {
    const { uuid } = props ?? {};

    return commentsDestroy(uuid, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommentsDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof commentsDestroy>>
>;

export type CommentsDestroyMutationError = unknown;
export type CommentsDestroyMutationVariables = { uuid: string };

export const createCommentsDestroy = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof commentsDestroy>>,
      TError,
      CommentsDestroyMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof commentsDestroy>>,
  TError,
  CommentsDestroyMutationVariables,
  TContext
> => {
  return createMutation(getCommentsDestroyMutationOptions(options));
};
export const getCommentsRepliesListUrl = (
  uuid: string,
  params?: CommentsRepliesListParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/comments/${uuid}/replies/?${stringifiedParams}`
    : `/api/comments/${uuid}/replies/`;
};

/**
 * These are the child comments for a parent comment identified by UUID.
 *
 * NEW - not tied to zpage
 */
export const commentsRepliesList = async (
  uuid: string,
  params?: CommentsRepliesListParams,
  options?: Parameters<typeof customInstance>[1],
): Promise<PaginatedCommentListList> => {
  return customInstance<PaginatedCommentListList>(
    getCommentsRepliesListUrl(uuid, params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getCommentsRepliesListQueryKey = (
  uuid: string,
  params?: CommentsRepliesListParams,
) => {
  return [
    `/api/comments/${uuid}/replies/`,
    ...(params ? [params] : []),
  ] as const;
};

export const getCommentsRepliesListQueryOptions = <
  TData = Awaited<ReturnType<typeof commentsRepliesList>>,
  TError = unknown,
>(
  uuid: string,
  params?: CommentsRepliesListParams,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof commentsRepliesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCommentsRepliesListQueryKey(uuid, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof commentsRepliesList>>
  > = ({ signal }) =>
    commentsRepliesList(uuid, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: uuid !== null && uuid !== undefined,
    ...queryOptions,
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof commentsRepliesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CommentsRepliesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof commentsRepliesList>>
>;
export type CommentsRepliesListQueryError = unknown;

export function createCommentsRepliesList<
  TData = Awaited<ReturnType<typeof commentsRepliesList>>,
  TError = unknown,
>(
  uuid: string,
  params?: CommentsRepliesListParams,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof commentsRepliesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCommentsRepliesListQueryOptions(
    uuid,
    params,
    options,
  );

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCommentsRepliesCreateUrl = (uuid: string) => {
  return `/api/comments/${uuid}/replies/`;
};

/**
 * These are the child comments for a parent comment identified by UUID.
 *
 * NEW - not tied to zpage
 */
export const commentsRepliesCreate = async (
  uuid: string,
  commentList: NonReadonly<CommentList>,
  options?: Parameters<typeof customInstance>[1],
): Promise<CommentList> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customInstance<CommentList>(getCommentsRepliesCreateUrl(uuid), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(commentList),
  });
};

export const getCommentsRepliesCreateMutationKey = () =>
  ["commentsRepliesCreate"] as const;

export const getCommentsRepliesCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof commentsRepliesCreate>>,
    TError,
    CommentsRepliesCreateMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof commentsRepliesCreate>>,
  TError,
  CommentsRepliesCreateMutationVariables,
  TContext
> => {
  const mutationKey = getCommentsRepliesCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof commentsRepliesCreate>>,
    CommentsRepliesCreateMutationVariables
  > = (props) => {
    const { uuid, data } = props ?? {};

    return commentsRepliesCreate(uuid, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommentsRepliesCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof commentsRepliesCreate>>
>;
export type CommentsRepliesCreateMutationBody = NonReadonly<CommentList>;
export type CommentsRepliesCreateMutationError = unknown;
export type CommentsRepliesCreateMutationVariables = {
  uuid: string;
  data: NonReadonly<CommentList>;
};

export const createCommentsRepliesCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof commentsRepliesCreate>>,
      TError,
      CommentsRepliesCreateMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof commentsRepliesCreate>>,
  TError,
  CommentsRepliesCreateMutationVariables,
  TContext
> => {
  return createMutation(getCommentsRepliesCreateMutationOptions(options));
};
export const getCommentsVoteCreateUrl = (uuid: string) => {
  return `/api/comments/${uuid}/vote/`;
};

export const commentsVoteCreate = async (
  uuid: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getCommentsVoteCreateUrl(uuid), {
    ...options,
    method: "POST",
  });
};

export const getCommentsVoteCreateMutationKey = () =>
  ["commentsVoteCreate"] as const;

export const getCommentsVoteCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof commentsVoteCreate>>,
    TError,
    CommentsVoteCreateMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof commentsVoteCreate>>,
  TError,
  CommentsVoteCreateMutationVariables,
  TContext
> => {
  const mutationKey = getCommentsVoteCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof commentsVoteCreate>>,
    CommentsVoteCreateMutationVariables
  > = (props) => {
    const { uuid } = props ?? {};

    return commentsVoteCreate(uuid, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommentsVoteCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof commentsVoteCreate>>
>;

export type CommentsVoteCreateMutationError = unknown;
export type CommentsVoteCreateMutationVariables = { uuid: string };

export const createCommentsVoteCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof commentsVoteCreate>>,
      TError,
      CommentsVoteCreateMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof commentsVoteCreate>>,
  TError,
  CommentsVoteCreateMutationVariables,
  TContext
> => {
  return createMutation(getCommentsVoteCreateMutationOptions(options));
};
