/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const kycChangeStatusCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/kyc/change-status`, method: 'POST', signal
    },
      options);
    }
  


export const getKycChangeStatusCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof kycChangeStatusCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof kycChangeStatusCreate>>, TError,void, TContext> => {

const mutationKey = ['kycChangeStatusCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof kycChangeStatusCreate>>, void> = () => {
          

          return  kycChangeStatusCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type KycChangeStatusCreateMutationResult = NonNullable<Awaited<ReturnType<typeof kycChangeStatusCreate>>>
    
    export type KycChangeStatusCreateMutationError = unknown

    export const createKycChangeStatusCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof kycChangeStatusCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof kycChangeStatusCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getKycChangeStatusCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const kycDeleteTaxFormDestroy = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/kyc/delete-tax-form`, method: 'DELETE'
    },
      options);
    }
  


export const getKycDeleteTaxFormDestroyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof kycDeleteTaxFormDestroy>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof kycDeleteTaxFormDestroy>>, TError,void, TContext> => {

const mutationKey = ['kycDeleteTaxFormDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof kycDeleteTaxFormDestroy>>, void> = () => {
          

          return  kycDeleteTaxFormDestroy(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type KycDeleteTaxFormDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof kycDeleteTaxFormDestroy>>>
    
    export type KycDeleteTaxFormDestroyMutationError = unknown

    export const createKycDeleteTaxFormDestroy = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof kycDeleteTaxFormDestroy>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof kycDeleteTaxFormDestroy>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getKycDeleteTaxFormDestroyMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const kycGetTaxFormFileRetrieve = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/kyc/get-tax-form-file`, method: 'GET', signal
    },
      options);
    }
  



export const getKycGetTaxFormFileRetrieveQueryKey = () => {
    return [
    `/api/kyc/get-tax-form-file`
    ] as const;
    }

    
export const getKycGetTaxFormFileRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof kycGetTaxFormFileRetrieve>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof kycGetTaxFormFileRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getKycGetTaxFormFileRetrieveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof kycGetTaxFormFileRetrieve>>> = ({ signal }) => kycGetTaxFormFileRetrieve(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof kycGetTaxFormFileRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type KycGetTaxFormFileRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof kycGetTaxFormFileRetrieve>>>
export type KycGetTaxFormFileRetrieveQueryError = unknown



export function createKycGetTaxFormFileRetrieve<TData = Awaited<ReturnType<typeof kycGetTaxFormFileRetrieve>>, TError = unknown>(
  options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof kycGetTaxFormFileRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getKycGetTaxFormFileRetrieveQueryOptions(options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const kycIdentityDocumentsRetrieve = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/kyc/identity-documents`, method: 'GET', signal
    },
      options);
    }
  



export const getKycIdentityDocumentsRetrieveQueryKey = () => {
    return [
    `/api/kyc/identity-documents`
    ] as const;
    }

    
export const getKycIdentityDocumentsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof kycIdentityDocumentsRetrieve>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof kycIdentityDocumentsRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getKycIdentityDocumentsRetrieveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof kycIdentityDocumentsRetrieve>>> = ({ signal }) => kycIdentityDocumentsRetrieve(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof kycIdentityDocumentsRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type KycIdentityDocumentsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof kycIdentityDocumentsRetrieve>>>
export type KycIdentityDocumentsRetrieveQueryError = unknown



export function createKycIdentityDocumentsRetrieve<TData = Awaited<ReturnType<typeof kycIdentityDocumentsRetrieve>>, TError = unknown>(
  options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof kycIdentityDocumentsRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getKycIdentityDocumentsRetrieveQueryOptions(options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const kycIdentityDocumentsCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/kyc/identity-documents`, method: 'POST', signal
    },
      options);
    }
  


export const getKycIdentityDocumentsCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof kycIdentityDocumentsCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof kycIdentityDocumentsCreate>>, TError,void, TContext> => {

const mutationKey = ['kycIdentityDocumentsCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof kycIdentityDocumentsCreate>>, void> = () => {
          

          return  kycIdentityDocumentsCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type KycIdentityDocumentsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof kycIdentityDocumentsCreate>>>
    
    export type KycIdentityDocumentsCreateMutationError = unknown

    export const createKycIdentityDocumentsCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof kycIdentityDocumentsCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof kycIdentityDocumentsCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getKycIdentityDocumentsCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const kycIdentityDocumentsDestroy = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/kyc/identity-documents`, method: 'DELETE'
    },
      options);
    }
  


export const getKycIdentityDocumentsDestroyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof kycIdentityDocumentsDestroy>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof kycIdentityDocumentsDestroy>>, TError,void, TContext> => {

const mutationKey = ['kycIdentityDocumentsDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof kycIdentityDocumentsDestroy>>, void> = () => {
          

          return  kycIdentityDocumentsDestroy(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type KycIdentityDocumentsDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof kycIdentityDocumentsDestroy>>>
    
    export type KycIdentityDocumentsDestroyMutationError = unknown

    export const createKycIdentityDocumentsDestroy = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof kycIdentityDocumentsDestroy>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof kycIdentityDocumentsDestroy>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getKycIdentityDocumentsDestroyMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const kycTaxFormSignatureRetrieve = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/kyc/tax-form-signature`, method: 'GET', signal
    },
      options);
    }
  



export const getKycTaxFormSignatureRetrieveQueryKey = () => {
    return [
    `/api/kyc/tax-form-signature`
    ] as const;
    }

    
export const getKycTaxFormSignatureRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof kycTaxFormSignatureRetrieve>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof kycTaxFormSignatureRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getKycTaxFormSignatureRetrieveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof kycTaxFormSignatureRetrieve>>> = ({ signal }) => kycTaxFormSignatureRetrieve(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof kycTaxFormSignatureRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type KycTaxFormSignatureRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof kycTaxFormSignatureRetrieve>>>
export type KycTaxFormSignatureRetrieveQueryError = unknown



export function createKycTaxFormSignatureRetrieve<TData = Awaited<ReturnType<typeof kycTaxFormSignatureRetrieve>>, TError = unknown>(
  options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof kycTaxFormSignatureRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getKycTaxFormSignatureRetrieveQueryOptions(options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const kycTaxFormSignatureCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/kyc/tax-form-signature`, method: 'POST', signal
    },
      options);
    }
  


export const getKycTaxFormSignatureCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof kycTaxFormSignatureCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof kycTaxFormSignatureCreate>>, TError,void, TContext> => {

const mutationKey = ['kycTaxFormSignatureCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof kycTaxFormSignatureCreate>>, void> = () => {
          

          return  kycTaxFormSignatureCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type KycTaxFormSignatureCreateMutationResult = NonNullable<Awaited<ReturnType<typeof kycTaxFormSignatureCreate>>>
    
    export type KycTaxFormSignatureCreateMutationError = unknown

    export const createKycTaxFormSignatureCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof kycTaxFormSignatureCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof kycTaxFormSignatureCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getKycTaxFormSignatureCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const kycUploadTaxFormCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/kyc/upload-tax-form`, method: 'POST', signal
    },
      options);
    }
  


export const getKycUploadTaxFormCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof kycUploadTaxFormCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof kycUploadTaxFormCreate>>, TError,void, TContext> => {

const mutationKey = ['kycUploadTaxFormCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof kycUploadTaxFormCreate>>, void> = () => {
          

          return  kycUploadTaxFormCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type KycUploadTaxFormCreateMutationResult = NonNullable<Awaited<ReturnType<typeof kycUploadTaxFormCreate>>>
    
    export type KycUploadTaxFormCreateMutationError = unknown

    export const createKycUploadTaxFormCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof kycUploadTaxFormCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof kycUploadTaxFormCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getKycUploadTaxFormCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const kycUserProfileRetrieve = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/kyc/user-profile`, method: 'GET', signal
    },
      options);
    }
  



export const getKycUserProfileRetrieveQueryKey = () => {
    return [
    `/api/kyc/user-profile`
    ] as const;
    }

    
export const getKycUserProfileRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof kycUserProfileRetrieve>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof kycUserProfileRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getKycUserProfileRetrieveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof kycUserProfileRetrieve>>> = ({ signal }) => kycUserProfileRetrieve(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof kycUserProfileRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type KycUserProfileRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof kycUserProfileRetrieve>>>
export type KycUserProfileRetrieveQueryError = unknown



export function createKycUserProfileRetrieve<TData = Awaited<ReturnType<typeof kycUserProfileRetrieve>>, TError = unknown>(
  options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof kycUserProfileRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getKycUserProfileRetrieveQueryOptions(options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const kycUserProfileCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/kyc/user-profile`, method: 'POST', signal
    },
      options);
    }
  


export const getKycUserProfileCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof kycUserProfileCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof kycUserProfileCreate>>, TError,void, TContext> => {

const mutationKey = ['kycUserProfileCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof kycUserProfileCreate>>, void> = () => {
          

          return  kycUserProfileCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type KycUserProfileCreateMutationResult = NonNullable<Awaited<ReturnType<typeof kycUserProfileCreate>>>
    
    export type KycUserProfileCreateMutationError = unknown

    export const createKycUserProfileCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof kycUserProfileCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof kycUserProfileCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getKycUserProfileCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    