# Generated by Django 4.2.11 on 2024-09-28 05:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrostGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_participants', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webauthn_public_key', models.TextField(help_text='The WebAuthn public key associated with this participant, used for authentication.')),
                ('webauthn_credential_id', models.TextField(blank=True, help_text="A unique identifier for the WebAuthn credential, ensuring secure reference to the participant's credential.", null=True, unique=True)),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(help_text='The group to which this participant belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='efm.frostgroup')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.CreateModel(
            name='WebAuthnChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge', models.TextField()),
                ('challenge_type', models.CharField(help_text="The type of WebAuthn challenge, either 'registration' or 'authentication'.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this challenge was created. Used for challenge expiration and auditing.')),
                ('participant', models.ForeignKey(help_text='The participant to whom this WebAuthn challenge was issued.', on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='efm.participant')),
            ],
        ),
    ]
