# Generated by Django 4.1.1 on 2022-09-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
