# Generated by Django 4.1.1 on 2022-09-29 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0002_alter_event_end_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='timeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='timelines.timeline'),
        ),
    ]
