# Generated by Django 4.1.1 on 2022-09-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_remove_timeline_events_event_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='media',
        ),
        migrations.AddField(
            model_name='event',
            name='media_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='media_credit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='media_url',
            field=models.URLField(blank=True),
        ),
    ]
