# Generated by Django 4.1.1 on 2022-09-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0004_remove_event_media_event_media_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='media',
        ),
        migrations.AddField(
            model_name='timeline',
            name='media_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='timeline',
            name='media_credit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='timeline',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
