/**
 * Generated by orval 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import { createQuery } from "@tanstack/svelte-query";
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
} from "@tanstack/svelte-query";

import type {
  SchemaRetrieve200Four,
  SchemaRetrieve200One,
  SchemaRetrieve200Three,
  SchemaRetrieve200Two,
  SchemaRetrieveParams,
} from "../f2z.schemas";

import { customInstance } from ".././mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getSchemaRetrieveUrl = (params?: SchemaRetrieveParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/schema/?${stringifiedParams}`
    : `/api/schema/`;
};

/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.
 *
 * - YAML: application/vnd.oai.openapi
 * - JSON: application/vnd.oai.openapi+json
 */
export const schemaRetrieve = async (
  params?: SchemaRetrieveParams,
  options?: Parameters<typeof customInstance>[1],
): Promise<
  | SchemaRetrieve200One
  | SchemaRetrieve200Two
  | SchemaRetrieve200Three
  | SchemaRetrieve200Four
> => {
  return customInstance<
    | SchemaRetrieve200One
    | SchemaRetrieve200Two
    | SchemaRetrieve200Three
    | SchemaRetrieve200Four
  >(getSchemaRetrieveUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getSchemaRetrieveQueryKey = (params?: SchemaRetrieveParams) => {
  return [`/api/schema/`, ...(params ? [params] : [])] as const;
};

export const getSchemaRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof schemaRetrieve>>,
  TError = unknown,
>(
  params?: SchemaRetrieveParams,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof schemaRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSchemaRetrieveQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof schemaRetrieve>>> = ({
    signal,
  }) => schemaRetrieve(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof schemaRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SchemaRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof schemaRetrieve>>
>;
export type SchemaRetrieveQueryError = unknown;

export function createSchemaRetrieve<
  TData = Awaited<ReturnType<typeof schemaRetrieve>>,
  TError = unknown,
>(
  params?: SchemaRetrieveParams,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof schemaRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSchemaRetrieveQueryOptions(params, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
