/**
 * Generated by orval 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import { createMutation, createQuery } from "@tanstack/svelte-query";
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
} from "@tanstack/svelte-query";

import type { Email } from "../f2z.schemas";

import { customInstance } from ".././mutator";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getEmailsAddCreateUrl = () => {
  return `/api/emails/add`;
};

export const emailsAddCreate = async (
  email: NonReadonly<Email>,
  options?: Parameters<typeof customInstance>[1],
): Promise<Email> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customInstance<Email>(getEmailsAddCreateUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(email),
  });
};

export const getEmailsAddCreateMutationKey = () => ["emailsAddCreate"] as const;

export const getEmailsAddCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof emailsAddCreate>>,
    TError,
    EmailsAddCreateMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof emailsAddCreate>>,
  TError,
  EmailsAddCreateMutationVariables,
  TContext
> => {
  const mutationKey = getEmailsAddCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof emailsAddCreate>>,
    EmailsAddCreateMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return emailsAddCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EmailsAddCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof emailsAddCreate>>
>;
export type EmailsAddCreateMutationBody = NonReadonly<Email>;
export type EmailsAddCreateMutationError = unknown;
export type EmailsAddCreateMutationVariables = { data: NonReadonly<Email> };

export const createEmailsAddCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof emailsAddCreate>>,
      TError,
      EmailsAddCreateMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof emailsAddCreate>>,
  TError,
  EmailsAddCreateMutationVariables,
  TContext
> => {
  return createMutation(getEmailsAddCreateMutationOptions(options));
};
export const getEmailsChangePasswordCreateUrl = () => {
  return `/api/emails/change-password`;
};

export const emailsChangePasswordCreate = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getEmailsChangePasswordCreateUrl(), {
    ...options,
    method: "POST",
  });
};

export const getEmailsChangePasswordCreateMutationKey = () =>
  ["emailsChangePasswordCreate"] as const;

export const getEmailsChangePasswordCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof emailsChangePasswordCreate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof emailsChangePasswordCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getEmailsChangePasswordCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof emailsChangePasswordCreate>>,
    void
  > = () => {
    return emailsChangePasswordCreate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EmailsChangePasswordCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof emailsChangePasswordCreate>>
>;

export type EmailsChangePasswordCreateMutationError = unknown;

export const createEmailsChangePasswordCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof emailsChangePasswordCreate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof emailsChangePasswordCreate>>,
  TError,
  void,
  TContext
> => {
  return createMutation(getEmailsChangePasswordCreateMutationOptions(options));
};
export const getEmailsConfirmRetrieveUrl = () => {
  return `/api/emails/confirm`;
};

export const emailsConfirmRetrieve = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getEmailsConfirmRetrieveUrl(), {
    ...options,
    method: "GET",
  });
};

export const getEmailsConfirmRetrieveQueryKey = () => {
  return [`/api/emails/confirm`] as const;
};

export const getEmailsConfirmRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof emailsConfirmRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    CreateQueryOptions<
      Awaited<ReturnType<typeof emailsConfirmRetrieve>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEmailsConfirmRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof emailsConfirmRetrieve>>
  > = ({ signal }) => emailsConfirmRetrieve({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof emailsConfirmRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type EmailsConfirmRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof emailsConfirmRetrieve>>
>;
export type EmailsConfirmRetrieveQueryError = unknown;

export function createEmailsConfirmRetrieve<
  TData = Awaited<ReturnType<typeof emailsConfirmRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof emailsConfirmRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getEmailsConfirmRetrieveQueryOptions(options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getEmailsDeleteDestroyUrl = () => {
  return `/api/emails/delete`;
};

export const emailsDeleteDestroy = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getEmailsDeleteDestroyUrl(), {
    ...options,
    method: "DELETE",
  });
};

export const getEmailsDeleteDestroyMutationKey = () =>
  ["emailsDeleteDestroy"] as const;

export const getEmailsDeleteDestroyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof emailsDeleteDestroy>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof emailsDeleteDestroy>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getEmailsDeleteDestroyMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof emailsDeleteDestroy>>,
    void
  > = () => {
    return emailsDeleteDestroy(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EmailsDeleteDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof emailsDeleteDestroy>>
>;

export type EmailsDeleteDestroyMutationError = unknown;

export const createEmailsDeleteDestroy = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof emailsDeleteDestroy>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof emailsDeleteDestroy>>,
  TError,
  void,
  TContext
> => {
  return createMutation(getEmailsDeleteDestroyMutationOptions(options));
};
export const getEmailsDoResetPasswordCreateUrl = () => {
  return `/api/emails/do-reset-password`;
};

export const emailsDoResetPasswordCreate = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getEmailsDoResetPasswordCreateUrl(), {
    ...options,
    method: "POST",
  });
};

export const getEmailsDoResetPasswordCreateMutationKey = () =>
  ["emailsDoResetPasswordCreate"] as const;

export const getEmailsDoResetPasswordCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof emailsDoResetPasswordCreate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof emailsDoResetPasswordCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getEmailsDoResetPasswordCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof emailsDoResetPasswordCreate>>,
    void
  > = () => {
    return emailsDoResetPasswordCreate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EmailsDoResetPasswordCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof emailsDoResetPasswordCreate>>
>;

export type EmailsDoResetPasswordCreateMutationError = unknown;

export const createEmailsDoResetPasswordCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof emailsDoResetPasswordCreate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof emailsDoResetPasswordCreate>>,
  TError,
  void,
  TContext
> => {
  return createMutation(getEmailsDoResetPasswordCreateMutationOptions(options));
};
export const getEmailsNotificationsCreateUrl = () => {
  return `/api/emails/notifications`;
};

export const emailsNotificationsCreate = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getEmailsNotificationsCreateUrl(), {
    ...options,
    method: "POST",
  });
};

export const getEmailsNotificationsCreateMutationKey = () =>
  ["emailsNotificationsCreate"] as const;

export const getEmailsNotificationsCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof emailsNotificationsCreate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof emailsNotificationsCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getEmailsNotificationsCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof emailsNotificationsCreate>>,
    void
  > = () => {
    return emailsNotificationsCreate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EmailsNotificationsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof emailsNotificationsCreate>>
>;

export type EmailsNotificationsCreateMutationError = unknown;

export const createEmailsNotificationsCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof emailsNotificationsCreate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof emailsNotificationsCreate>>,
  TError,
  void,
  TContext
> => {
  return createMutation(getEmailsNotificationsCreateMutationOptions(options));
};
export const getEmailsOptOutRetrieveUrl = (email: string) => {
  return `/api/emails/opt-out/${email}`;
};

export const emailsOptOutRetrieve = async (
  email: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getEmailsOptOutRetrieveUrl(email), {
    ...options,
    method: "GET",
  });
};

export const getEmailsOptOutRetrieveQueryKey = (email: string) => {
  return [`/api/emails/opt-out/${email}`] as const;
};

export const getEmailsOptOutRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof emailsOptOutRetrieve>>,
  TError = unknown,
>(
  email: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof emailsOptOutRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getEmailsOptOutRetrieveQueryKey(email);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof emailsOptOutRetrieve>>
  > = ({ signal }) =>
    emailsOptOutRetrieve(email, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: email !== null && email !== undefined,
    ...queryOptions,
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof emailsOptOutRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type EmailsOptOutRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof emailsOptOutRetrieve>>
>;
export type EmailsOptOutRetrieveQueryError = unknown;

export function createEmailsOptOutRetrieve<
  TData = Awaited<ReturnType<typeof emailsOptOutRetrieve>>,
  TError = unknown,
>(
  email: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof emailsOptOutRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getEmailsOptOutRetrieveQueryOptions(email, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getEmailsPasswordIsSetRetrieveUrl = () => {
  return `/api/emails/password-is-set`;
};

export const emailsPasswordIsSetRetrieve = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getEmailsPasswordIsSetRetrieveUrl(), {
    ...options,
    method: "GET",
  });
};

export const getEmailsPasswordIsSetRetrieveQueryKey = () => {
  return [`/api/emails/password-is-set`] as const;
};

export const getEmailsPasswordIsSetRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof emailsPasswordIsSetRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    CreateQueryOptions<
      Awaited<ReturnType<typeof emailsPasswordIsSetRetrieve>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getEmailsPasswordIsSetRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof emailsPasswordIsSetRetrieve>>
  > = ({ signal }) =>
    emailsPasswordIsSetRetrieve({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof emailsPasswordIsSetRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type EmailsPasswordIsSetRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof emailsPasswordIsSetRetrieve>>
>;
export type EmailsPasswordIsSetRetrieveQueryError = unknown;

export function createEmailsPasswordIsSetRetrieve<
  TData = Awaited<ReturnType<typeof emailsPasswordIsSetRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof emailsPasswordIsSetRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getEmailsPasswordIsSetRetrieveQueryOptions(options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getEmailsPublicCreateUrl = () => {
  return `/api/emails/public`;
};

export const emailsPublicCreate = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getEmailsPublicCreateUrl(), {
    ...options,
    method: "POST",
  });
};

export const getEmailsPublicCreateMutationKey = () =>
  ["emailsPublicCreate"] as const;

export const getEmailsPublicCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof emailsPublicCreate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof emailsPublicCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getEmailsPublicCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof emailsPublicCreate>>,
    void
  > = () => {
    return emailsPublicCreate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EmailsPublicCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof emailsPublicCreate>>
>;

export type EmailsPublicCreateMutationError = unknown;

export const createEmailsPublicCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof emailsPublicCreate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof emailsPublicCreate>>,
  TError,
  void,
  TContext
> => {
  return createMutation(getEmailsPublicCreateMutationOptions(options));
};
export const getEmailsResendCreateUrl = () => {
  return `/api/emails/resend`;
};

export const emailsResendCreate = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getEmailsResendCreateUrl(), {
    ...options,
    method: "POST",
  });
};

export const getEmailsResendCreateMutationKey = () =>
  ["emailsResendCreate"] as const;

export const getEmailsResendCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof emailsResendCreate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof emailsResendCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getEmailsResendCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof emailsResendCreate>>,
    void
  > = () => {
    return emailsResendCreate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EmailsResendCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof emailsResendCreate>>
>;

export type EmailsResendCreateMutationError = unknown;

export const createEmailsResendCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof emailsResendCreate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof emailsResendCreate>>,
  TError,
  void,
  TContext
> => {
  return createMutation(getEmailsResendCreateMutationOptions(options));
};
export const getEmailsResetPasswordCreateUrl = () => {
  return `/api/emails/reset-password`;
};

export const emailsResetPasswordCreate = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getEmailsResetPasswordCreateUrl(), {
    ...options,
    method: "POST",
  });
};

export const getEmailsResetPasswordCreateMutationKey = () =>
  ["emailsResetPasswordCreate"] as const;

export const getEmailsResetPasswordCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof emailsResetPasswordCreate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof emailsResetPasswordCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getEmailsResetPasswordCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof emailsResetPasswordCreate>>,
    void
  > = () => {
    return emailsResetPasswordCreate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EmailsResetPasswordCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof emailsResetPasswordCreate>>
>;

export type EmailsResetPasswordCreateMutationError = unknown;

export const createEmailsResetPasswordCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof emailsResetPasswordCreate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof emailsResetPasswordCreate>>,
  TError,
  void,
  TContext
> => {
  return createMutation(getEmailsResetPasswordCreateMutationOptions(options));
};
export const getEmailsStatusRetrieveUrl = () => {
  return `/api/emails/status`;
};

export const emailsStatusRetrieve = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getEmailsStatusRetrieveUrl(), {
    ...options,
    method: "GET",
  });
};

export const getEmailsStatusRetrieveQueryKey = () => {
  return [`/api/emails/status`] as const;
};

export const getEmailsStatusRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof emailsStatusRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    CreateQueryOptions<
      Awaited<ReturnType<typeof emailsStatusRetrieve>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEmailsStatusRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof emailsStatusRetrieve>>
  > = ({ signal }) => emailsStatusRetrieve({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof emailsStatusRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type EmailsStatusRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof emailsStatusRetrieve>>
>;
export type EmailsStatusRetrieveQueryError = unknown;

export function createEmailsStatusRetrieve<
  TData = Awaited<ReturnType<typeof emailsStatusRetrieve>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof emailsStatusRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getEmailsStatusRetrieveQueryOptions(options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
