/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const twitterDeleteDestroy = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/twitter/delete`, method: 'DELETE'
    },
      options);
    }
  


export const getTwitterDeleteDestroyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof twitterDeleteDestroy>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof twitterDeleteDestroy>>, TError,void, TContext> => {

const mutationKey = ['twitterDeleteDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof twitterDeleteDestroy>>, void> = () => {
          

          return  twitterDeleteDestroy(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TwitterDeleteDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof twitterDeleteDestroy>>>
    
    export type TwitterDeleteDestroyMutationError = unknown

    export const createTwitterDeleteDestroy = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof twitterDeleteDestroy>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof twitterDeleteDestroy>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getTwitterDeleteDestroyMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const twitterPublicStatusRetrieve = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/twitter/public-status/`, method: 'GET', signal
    },
      options);
    }
  



export const getTwitterPublicStatusRetrieveQueryKey = () => {
    return [
    `/api/twitter/public-status/`
    ] as const;
    }

    
export const getTwitterPublicStatusRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof twitterPublicStatusRetrieve>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof twitterPublicStatusRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTwitterPublicStatusRetrieveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof twitterPublicStatusRetrieve>>> = ({ signal }) => twitterPublicStatusRetrieve(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof twitterPublicStatusRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type TwitterPublicStatusRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof twitterPublicStatusRetrieve>>>
export type TwitterPublicStatusRetrieveQueryError = unknown



export function createTwitterPublicStatusRetrieve<TData = Awaited<ReturnType<typeof twitterPublicStatusRetrieve>>, TError = unknown>(
  options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof twitterPublicStatusRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getTwitterPublicStatusRetrieveQueryOptions(options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const twitterPublicStatusUpdate = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/twitter/public-status/`, method: 'PUT'
    },
      options);
    }
  


export const getTwitterPublicStatusUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof twitterPublicStatusUpdate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof twitterPublicStatusUpdate>>, TError,void, TContext> => {

const mutationKey = ['twitterPublicStatusUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof twitterPublicStatusUpdate>>, void> = () => {
          

          return  twitterPublicStatusUpdate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TwitterPublicStatusUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof twitterPublicStatusUpdate>>>
    
    export type TwitterPublicStatusUpdateMutationError = unknown

    export const createTwitterPublicStatusUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof twitterPublicStatusUpdate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof twitterPublicStatusUpdate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getTwitterPublicStatusUpdateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const twitterPublicStatusPartialUpdate = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/twitter/public-status/`, method: 'PATCH'
    },
      options);
    }
  


export const getTwitterPublicStatusPartialUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof twitterPublicStatusPartialUpdate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof twitterPublicStatusPartialUpdate>>, TError,void, TContext> => {

const mutationKey = ['twitterPublicStatusPartialUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof twitterPublicStatusPartialUpdate>>, void> = () => {
          

          return  twitterPublicStatusPartialUpdate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TwitterPublicStatusPartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof twitterPublicStatusPartialUpdate>>>
    
    export type TwitterPublicStatusPartialUpdateMutationError = unknown

    export const createTwitterPublicStatusPartialUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof twitterPublicStatusPartialUpdate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof twitterPublicStatusPartialUpdate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getTwitterPublicStatusPartialUpdateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const twitterV1AccessTokenRetrieve = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/twitter/v1/access-token`, method: 'GET', signal
    },
      options);
    }
  



export const getTwitterV1AccessTokenRetrieveQueryKey = () => {
    return [
    `/api/twitter/v1/access-token`
    ] as const;
    }

    
export const getTwitterV1AccessTokenRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof twitterV1AccessTokenRetrieve>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof twitterV1AccessTokenRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTwitterV1AccessTokenRetrieveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof twitterV1AccessTokenRetrieve>>> = ({ signal }) => twitterV1AccessTokenRetrieve(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof twitterV1AccessTokenRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type TwitterV1AccessTokenRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof twitterV1AccessTokenRetrieve>>>
export type TwitterV1AccessTokenRetrieveQueryError = unknown



export function createTwitterV1AccessTokenRetrieve<TData = Awaited<ReturnType<typeof twitterV1AccessTokenRetrieve>>, TError = unknown>(
  options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof twitterV1AccessTokenRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getTwitterV1AccessTokenRetrieveQueryOptions(options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const twitterV1RequestTokenCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/twitter/v1/request-token`, method: 'POST', signal
    },
      options);
    }
  


export const getTwitterV1RequestTokenCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof twitterV1RequestTokenCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof twitterV1RequestTokenCreate>>, TError,void, TContext> => {

const mutationKey = ['twitterV1RequestTokenCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof twitterV1RequestTokenCreate>>, void> = () => {
          

          return  twitterV1RequestTokenCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TwitterV1RequestTokenCreateMutationResult = NonNullable<Awaited<ReturnType<typeof twitterV1RequestTokenCreate>>>
    
    export type TwitterV1RequestTokenCreateMutationError = unknown

    export const createTwitterV1RequestTokenCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof twitterV1RequestTokenCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof twitterV1RequestTokenCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getTwitterV1RequestTokenCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    