import { expect, test, type Page } from "@playwright/test";

async function openEmptyWallet(page: Page) {
  await page.addInitScript(() => {
    localStorage.setItem("zuuli.mock.wallet-scenario", "empty");
    localStorage.removeItem("zuuli.mock.created-wallet");
    localStorage.removeItem("zuuli.mock.backup-required");
  });
  await page.goto("/wallet");
  await expect(page.getByText("Set up your Zcash wallet")).toBeVisible();
}

test("new-wallet UI has no length choice and reveals 24 words", async ({
  page,
}) => {
  await openEmptyWallet(page);

  await expect(page.getByText("Recovery phrase length")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "12 words" })).toHaveCount(0);
  await expect(
    page.getByText(
      "New wallets always use a 24-word recovery phrase generated by the native wallet engine.",
    ),
  ).toBeVisible();

  await page.getByRole("button", { name: "Create wallet" }).click();
  await page
    .getByRole("button", { name: "Authenticate to reveal phrase" })
    .click();
  await expect(page.locator("ol[aria-hidden='true'] li")).toHaveCount(24);
});

test("wallet restore accepts every supported BIP39 word count and no others", async ({
  page,
}) => {
  await openEmptyWallet(page);
  await page.getByRole("tab", { name: "Restore" }).click();

  const phrase = page.getByLabel("Recovery phrase");
  const restore = page.getByRole("button", { name: "Restore wallet" });
  for (const wordCount of [12, 15, 18, 21, 24]) {
    await phrase.fill(
      Array.from({ length: wordCount }, () => "word").join(" "),
    );
    await expect(restore).toBeEnabled();
  }
  for (const wordCount of [11, 13, 16, 19, 22, 25]) {
    await phrase.fill(
      Array.from({ length: wordCount }, () => "word").join(" "),
    );
    await expect(restore).toBeDisabled();
  }
});

test("identity restore accepts every supported BIP39 word count and no others", async ({
  page,
}) => {
  await page.addInitScript(() => {
    localStorage.removeItem("zuuli.knox.token");
    localStorage.setItem("zuuli.mock.wallet-scenario", "empty");
  });
  await page.goto("/login");
  await page.getByRole("button", { name: "Zcash", exact: true }).click();
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByRole("button", { name: "Use existing identity" }).click();

  const phrase = page.getByLabel("Recovery phrase");
  const restore = page.getByRole("button", { name: "Restore and continue" });
  for (const wordCount of [12, 15, 18, 21, 24]) {
    await phrase.fill(
      Array.from({ length: wordCount }, () => "word").join(" "),
    );
    await expect(restore).toBeEnabled();
  }
  for (const wordCount of [11, 13, 16, 19, 22, 25]) {
    await phrase.fill(
      Array.from({ length: wordCount }, () => "word").join(" "),
    );
    await expect(restore).toBeDisabled();
  }
});
