pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "tauri-plugin-zcash"
include(":tauri-android")
project(":tauri-android").projectDir = new File(rootDir, ".tauri/tauri-api")
