/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  G12fSeriesMineListParams,
  PaginatedSeriesEditList,
  PatchedSeriesEdit,
  SeriesEdit
} from '../f2z.schemas';

import { customInstance } from '.././mutator';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const g12fSeriesMineList = (
    params?: G12fSeriesMineListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedSeriesEditList>(
      {url: `/api/g12f/series/mine/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getG12fSeriesMineListQueryKey = (params?: G12fSeriesMineListParams,) => {
    return [
    `/api/g12f/series/mine/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getG12fSeriesMineListQueryOptions = <TData = Awaited<ReturnType<typeof g12fSeriesMineList>>, TError = unknown>(params?: G12fSeriesMineListParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof g12fSeriesMineList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getG12fSeriesMineListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof g12fSeriesMineList>>> = ({ signal }) => g12fSeriesMineList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof g12fSeriesMineList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type G12fSeriesMineListQueryResult = NonNullable<Awaited<ReturnType<typeof g12fSeriesMineList>>>
export type G12fSeriesMineListQueryError = unknown



export function createG12fSeriesMineList<TData = Awaited<ReturnType<typeof g12fSeriesMineList>>, TError = unknown>(
 params?: G12fSeriesMineListParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof g12fSeriesMineList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getG12fSeriesMineListQueryOptions(params,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const g12fSeriesMineCreate = (
    seriesEdit: NonReadonly<SeriesEdit>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SeriesEdit>(
      {url: `/api/g12f/series/mine/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: seriesEdit, signal
    },
      options);
    }
  


export const getG12fSeriesMineCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof g12fSeriesMineCreate>>, TError,{data: NonReadonly<SeriesEdit>}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof g12fSeriesMineCreate>>, TError,{data: NonReadonly<SeriesEdit>}, TContext> => {

const mutationKey = ['g12fSeriesMineCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof g12fSeriesMineCreate>>, {data: NonReadonly<SeriesEdit>}> = (props) => {
          const {data} = props ?? {};

          return  g12fSeriesMineCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type G12fSeriesMineCreateMutationResult = NonNullable<Awaited<ReturnType<typeof g12fSeriesMineCreate>>>
    export type G12fSeriesMineCreateMutationBody = NonReadonly<SeriesEdit>
    export type G12fSeriesMineCreateMutationError = unknown

    export const createG12fSeriesMineCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof g12fSeriesMineCreate>>, TError,{data: NonReadonly<SeriesEdit>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof g12fSeriesMineCreate>>,
        TError,
        {data: NonReadonly<SeriesEdit>},
        TContext
      > => {

      const mutationOptions = getG12fSeriesMineCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const g12fSeriesMineRetrieve = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SeriesEdit>(
      {url: `/api/g12f/series/mine/${id}/`, method: 'GET', signal
    },
      options);
    }
  



export const getG12fSeriesMineRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/g12f/series/mine/${id}/`
    ] as const;
    }

    
export const getG12fSeriesMineRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof g12fSeriesMineRetrieve>>, TError = unknown>(id: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof g12fSeriesMineRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getG12fSeriesMineRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof g12fSeriesMineRetrieve>>> = ({ signal }) => g12fSeriesMineRetrieve(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof g12fSeriesMineRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type G12fSeriesMineRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof g12fSeriesMineRetrieve>>>
export type G12fSeriesMineRetrieveQueryError = unknown



export function createG12fSeriesMineRetrieve<TData = Awaited<ReturnType<typeof g12fSeriesMineRetrieve>>, TError = unknown>(
 id: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof g12fSeriesMineRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getG12fSeriesMineRetrieveQueryOptions(id,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const g12fSeriesMineUpdate = (
    id: string,
    seriesEdit: NonReadonly<SeriesEdit>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<SeriesEdit>(
      {url: `/api/g12f/series/mine/${id}/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: seriesEdit
    },
      options);
    }
  


export const getG12fSeriesMineUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof g12fSeriesMineUpdate>>, TError,{id: string;data: NonReadonly<SeriesEdit>}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof g12fSeriesMineUpdate>>, TError,{id: string;data: NonReadonly<SeriesEdit>}, TContext> => {

const mutationKey = ['g12fSeriesMineUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof g12fSeriesMineUpdate>>, {id: string;data: NonReadonly<SeriesEdit>}> = (props) => {
          const {id,data} = props ?? {};

          return  g12fSeriesMineUpdate(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type G12fSeriesMineUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof g12fSeriesMineUpdate>>>
    export type G12fSeriesMineUpdateMutationBody = NonReadonly<SeriesEdit>
    export type G12fSeriesMineUpdateMutationError = unknown

    export const createG12fSeriesMineUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof g12fSeriesMineUpdate>>, TError,{id: string;data: NonReadonly<SeriesEdit>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof g12fSeriesMineUpdate>>,
        TError,
        {id: string;data: NonReadonly<SeriesEdit>},
        TContext
      > => {

      const mutationOptions = getG12fSeriesMineUpdateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const g12fSeriesMinePartialUpdate = (
    id: string,
    patchedSeriesEdit: NonReadonly<PatchedSeriesEdit>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<SeriesEdit>(
      {url: `/api/g12f/series/mine/${id}/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedSeriesEdit
    },
      options);
    }
  


export const getG12fSeriesMinePartialUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof g12fSeriesMinePartialUpdate>>, TError,{id: string;data: NonReadonly<PatchedSeriesEdit>}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof g12fSeriesMinePartialUpdate>>, TError,{id: string;data: NonReadonly<PatchedSeriesEdit>}, TContext> => {

const mutationKey = ['g12fSeriesMinePartialUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof g12fSeriesMinePartialUpdate>>, {id: string;data: NonReadonly<PatchedSeriesEdit>}> = (props) => {
          const {id,data} = props ?? {};

          return  g12fSeriesMinePartialUpdate(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type G12fSeriesMinePartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof g12fSeriesMinePartialUpdate>>>
    export type G12fSeriesMinePartialUpdateMutationBody = NonReadonly<PatchedSeriesEdit>
    export type G12fSeriesMinePartialUpdateMutationError = unknown

    export const createG12fSeriesMinePartialUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof g12fSeriesMinePartialUpdate>>, TError,{id: string;data: NonReadonly<PatchedSeriesEdit>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof g12fSeriesMinePartialUpdate>>,
        TError,
        {id: string;data: NonReadonly<PatchedSeriesEdit>},
        TContext
      > => {

      const mutationOptions = getG12fSeriesMinePartialUpdateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const g12fSeriesMineDestroy = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/g12f/series/mine/${id}/`, method: 'DELETE'
    },
      options);
    }
  


export const getG12fSeriesMineDestroyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof g12fSeriesMineDestroy>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof g12fSeriesMineDestroy>>, TError,{id: string}, TContext> => {

const mutationKey = ['g12fSeriesMineDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof g12fSeriesMineDestroy>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  g12fSeriesMineDestroy(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type G12fSeriesMineDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof g12fSeriesMineDestroy>>>
    
    export type G12fSeriesMineDestroyMutationError = unknown

    export const createG12fSeriesMineDestroy = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof g12fSeriesMineDestroy>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof g12fSeriesMineDestroy>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getG12fSeriesMineDestroyMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve series by zpage
 */
export const g12fZpageSeriesRetrieve = (
    free2zaddr: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/g12f/zpage/${free2zaddr}/series/`, method: 'GET', signal
    },
      options);
    }
  



export const getG12fZpageSeriesRetrieveQueryKey = (free2zaddr?: string,) => {
    return [
    `/api/g12f/zpage/${free2zaddr}/series/`
    ] as const;
    }

    
export const getG12fZpageSeriesRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof g12fZpageSeriesRetrieve>>, TError = unknown>(free2zaddr: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof g12fZpageSeriesRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getG12fZpageSeriesRetrieveQueryKey(free2zaddr);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof g12fZpageSeriesRetrieve>>> = ({ signal }) => g12fZpageSeriesRetrieve(free2zaddr, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(free2zaddr), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof g12fZpageSeriesRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type G12fZpageSeriesRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof g12fZpageSeriesRetrieve>>>
export type G12fZpageSeriesRetrieveQueryError = unknown



export function createG12fZpageSeriesRetrieve<TData = Awaited<ReturnType<typeof g12fZpageSeriesRetrieve>>, TError = unknown>(
 free2zaddr: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof g12fZpageSeriesRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getG12fZpageSeriesRetrieveQueryOptions(free2zaddr,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




