/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import {
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getTypeRetrieve = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/get-type/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTypeRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/get-type/${id}`
    ] as const;
    }

    
export const getGetTypeRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof getTypeRetrieve>>, TError = unknown>(id: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getTypeRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTypeRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTypeRetrieve>>> = ({ signal }) => getTypeRetrieve(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getTypeRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetTypeRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof getTypeRetrieve>>>
export type GetTypeRetrieveQueryError = unknown



export function createGetTypeRetrieve<TData = Awaited<ReturnType<typeof getTypeRetrieve>>, TError = unknown>(
 id: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getTypeRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetTypeRetrieveQueryOptions(id,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



