//! One device, built the way a real one is.
//!
//! # Why the credentials here come from `f2z-msg-identity`
//!
//! Nothing in these tests hand-rolls a `DeviceCredential`. Each one is issued by
//! `AccountKeys::from_seed` → `IdentitySigningKey::issue_device_credential`,
//! which is the code path a ZUULI enrollment actually takes
//! (`CLIENT-CONTRACT.md` §2.2). That makes this directory the **coordination
//! test** between #694's crate and this one: if the two ever disagree about the
//! structure of a credential, the engine stops accepting credentials the
//! identity crate issues — here, in CI, rather than on somebody's phone.
//!
//! # Why the device signer belongs to this crate
//!
//! MLS framing is signed only by **libcrux** through
//! [`f2z_msg_mls::DeviceSigner`], as ADR 0001's single crypto core requires.
//! `f2z-msg-identity` owns the account hierarchy and credential issuer, but it
//! exposes no `ed25519-dalek` MLS-signing path. These tests therefore use the
//! identity crate for the **account** half of §4.2 and `DeviceSigner` for the
//! **device** half.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    dead_code
)]

use f2z_codec::types::{Digest, PublicKey, ShortBytes};
use f2z_kt_core::entry::{DeviceCredential, DeviceRevocation, DirectoryEntryTBS, EntryKind};
use f2z_kt_core::types::{Handle, KemPublicKey, LogId};
use f2z_msg_identity::{AccountKeys, DeviceCredentialRequest};
use f2z_msg_mls::{DeviceSigner, MlsEngine};
use f2z_msg_store::MemoryBackend;

/// A fixed instant, so nothing in these tests depends on a clock.
pub const NOW: u64 = 1_700_000_000_000;

/// The X-Wing hybrid public key an MLS `KeyPackage` would carry.
///
/// A stand-in: the engine does not read `device_kem_pk` — the HPKE init key MLS
/// actually uses is the one inside the `KeyPackage`, generated by OpenMLS — so a
/// fixed 1216-byte value keeps these tests about the *binding* rather than about
/// KEM plumbing. `KT.md` §4.1 requires only that it is non-empty.
pub fn kem_public_key(seed: u8) -> KemPublicKey {
    KemPublicKey::new(vec![seed; 1216]).unwrap()
}

/// Issue a credential the way enrollment does: a seed-derived account key
/// binding a CSPRNG-generated device key.
pub fn issue_credential(
    handle: &str,
    account_seed: u8,
    device_seed: u8,
    not_before_ms: u64,
    not_after_ms: u64,
) -> (DeviceCredential, DeviceSigner) {
    // A 64-byte BIP-39-shaped seed. `AccountKeys::from_seed` is §4.2's
    // `S → MSK → account_node`, and it is deliberately the only way to get an
    // `IdentitySigningKey`.
    let seed = [account_seed; 64];
    let account = AccountKeys::from_seed(&seed, 0).unwrap();

    let signer = DeviceSigner::from_private_key([device_seed; 32]).unwrap();

    let credential = account
        .identity
        .issue_device_credential(&DeviceCredentialRequest {
            handle: Handle::new(handle.as_bytes().to_vec()).unwrap(),
            device_pk: PublicKey::new(*signer.public_key()),
            device_kem_pk: kem_public_key(device_seed),
            not_before_ms,
            not_after_ms,
        })
        .unwrap();

    (credential, signer)
}

/// One device: its own store, its own keys, its own credential.
pub fn device(handle: &str, account_seed: u8, device_seed: u8) -> MlsEngine<MemoryBackend> {
    let (credential, signer) = issue_credential(
        handle,
        account_seed,
        device_seed,
        NOW - 1_000_000,
        NOW + 1_000_000,
    );
    MlsEngine::new(MemoryBackend::new(), signer, credential, NOW).unwrap()
}

/// A `DirectoryEntryTBS` that publishes exactly these credentials.
///
/// The tests build one directly rather than through a log, because what they
/// are about is `f2z-msg-mls`'s obligation — check the fetched package against
/// whatever the log proved — and not the log's. The plugin's two-process
/// harness runs the same check against a real `f2z-kt` entry.
pub fn directory_entry(credentials: &[DeviceCredential]) -> DirectoryEntryTBS {
    let first = credentials.first().expect("at least one credential");
    DirectoryEntryTBS {
        label: ShortBytes::new(f2z_kt_core::labels::LABEL_ENTRY.to_vec()).unwrap(),
        kt_version: 1,
        log_id: LogId::new([0x11; 32]),
        handle: first.credential.handle.clone(),
        entry_version: 1,
        kind: EntryKind::SameKey,
        identity_pk: first.credential.identity_pk,
        directory_auth_pk: PublicKey::new([0x22; 32]),
        devices: credentials.to_vec().into(),
        revocations: Vec::new().into(),
        contact_endpoints: Vec::new().into(),
        prev_entry_hash: Digest::new([0; 32]),
        no_reset: 0,
        created_at_ms: NOW,
    }
}

/// The same entry, with one device revoked.
pub fn with_revocation(entry: &DirectoryEntryTBS, device_pk: PublicKey) -> DirectoryEntryTBS {
    let mut entry = entry.clone();
    entry.revocations = vec![DeviceRevocation {
        device_pk,
        revoked_at_ms: NOW,
        reason: ShortBytes::new(b"lost".to_vec()).unwrap(),
    }]
    .into();
    entry
}
