//! One device, built the way a real one is.
//!
//! # Why the credentials here come from `f2z-msg-identity`
//!
//! Nothing in these tests hand-rolls a `DeviceCredential`. Each one is issued by
//! `AccountKeys::from_seed` → `IdentitySigningKey::issue_device_credential`,
//! which is the code path a ZUULI enrollment actually takes
//! (`CLIENT-CONTRACT.md` §2.2). That makes this directory the **coordination
//! test** between #694's crate and this one: if the two ever disagree about the
//! structure of a credential, the engine stops accepting credentials the
//! identity crate issues — here, in CI, rather than on somebody's phone.
//!
//! # The one place the two crates do not meet, stated
//!
//! `f2z-msg-identity::DeviceSignatureKey` signs MLS framing with
//! **`ed25519-dalek`** (`sign_mls_content`), and this engine signs it with
//! **libcrux** ([`f2z_msg_mls::DeviceSigner`]) — which is what closes
//! [#693](https://github.com/free2z/zuu/issues/693) and what ADR 0001's single
//! crypto core requires. `DeviceSignatureKey` does not expose its private bytes
//! (correctly), so the two cannot be bridged from outside, and these tests
//! therefore use the identity crate for the **account** half of §4.2 and
//! `DeviceSigner` for the **device** half.
//!
//! That is a real seam and it needs reconciling: either `DeviceSignatureKey`
//! signs through libcrux, or it stops offering `sign_mls_content`. It is called
//! out in the pull request rather than papered over here.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    dead_code
)]

use f2z_codec::types::PublicKey;
use f2z_kt_core::entry::DeviceCredential;
use f2z_kt_core::types::{Handle, KemPublicKey};
use f2z_msg_identity::{AccountKeys, DeviceCredentialRequest};
use f2z_msg_mls::{DeviceSigner, MlsEngine};
use f2z_msg_store::MemoryBackend;

/// A fixed instant, so nothing in these tests depends on a clock.
pub const NOW: u64 = 1_700_000_000_000;

/// The X-Wing hybrid public key an MLS `KeyPackage` would carry.
///
/// A stand-in: the engine does not read `device_kem_pk` — the HPKE init key MLS
/// actually uses is the one inside the `KeyPackage`, generated by OpenMLS — so a
/// fixed 1216-byte value keeps these tests about the *binding* rather than about
/// KEM plumbing. `KT.md` §4.1 requires only that it is non-empty.
pub fn kem_public_key(seed: u8) -> KemPublicKey {
    KemPublicKey::new(vec![seed; 1216]).unwrap()
}

/// Issue a credential the way enrollment does: a seed-derived account key
/// binding a CSPRNG-generated device key.
pub fn issue_credential(
    handle: &str,
    account_seed: u8,
    device_seed: u8,
    not_before_ms: u64,
    not_after_ms: u64,
) -> (DeviceCredential, DeviceSigner) {
    // A 64-byte BIP-39-shaped seed. `AccountKeys::from_seed` is §4.2's
    // `S → MSK → account_node`, and it is deliberately the only way to get an
    // `IdentitySigningKey`.
    let seed = [account_seed; 64];
    let account = AccountKeys::from_seed(&seed, 0).unwrap();

    let signer = DeviceSigner::from_private_key([device_seed; 32]);

    let credential = account
        .identity
        .issue_device_credential(&DeviceCredentialRequest {
            handle: Handle::new(handle.as_bytes().to_vec()).unwrap(),
            device_pk: PublicKey::new(*signer.public_key()),
            device_kem_pk: kem_public_key(device_seed),
            not_before_ms,
            not_after_ms,
        })
        .unwrap();

    (credential, signer)
}

/// One device: its own store, its own keys, its own credential.
pub fn device(handle: &str, account_seed: u8, device_seed: u8) -> MlsEngine<MemoryBackend> {
    let (credential, signer) = issue_credential(
        handle,
        account_seed,
        device_seed,
        NOW - 1_000_000,
        NOW + 1_000_000,
    );
    MlsEngine::new(MemoryBackend::new(), signer, credential, NOW).unwrap()
}
