/**
 * Generated by orval 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import { createQuery } from "@tanstack/svelte-query";
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
} from "@tanstack/svelte-query";

import type {
  CreatorDetail,
  CreatorListParams,
  PaginatedCreatorListList,
} from "../f2z.schemas";

import { customInstance } from ".././mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getCreatorListUrl = (params?: CreatorListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/creator/?${stringifiedParams}`
    : `/api/creator/`;
};

/**
 * List Creators on Free2z
 */
export const creatorList = async (
  params?: CreatorListParams,
  options?: Parameters<typeof customInstance>[1],
): Promise<PaginatedCreatorListList> => {
  return customInstance<PaginatedCreatorListList>(getCreatorListUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getCreatorListQueryKey = (params?: CreatorListParams) => {
  return [`/api/creator/`, ...(params ? [params] : [])] as const;
};

export const getCreatorListQueryOptions = <
  TData = Awaited<ReturnType<typeof creatorList>>,
  TError = unknown,
>(
  params?: CreatorListParams,
  options?: {
    query?: Partial<
      CreateQueryOptions<Awaited<ReturnType<typeof creatorList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCreatorListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof creatorList>>> = ({
    signal,
  }) => creatorList(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof creatorList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CreatorListQueryResult = NonNullable<
  Awaited<ReturnType<typeof creatorList>>
>;
export type CreatorListQueryError = unknown;

export function createCreatorList<
  TData = Awaited<ReturnType<typeof creatorList>>,
  TError = unknown,
>(
  params?: CreatorListParams,
  options?: {
    query?: Partial<
      CreateQueryOptions<Awaited<ReturnType<typeof creatorList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCreatorListQueryOptions(params, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCreatorRetrieveUrl = (usernameIexact: string) => {
  return `/api/creator/${usernameIexact}/`;
};

/**
 * List Creators on Free2z
 */
export const creatorRetrieve = async (
  usernameIexact: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<CreatorDetail> => {
  return customInstance<CreatorDetail>(getCreatorRetrieveUrl(usernameIexact), {
    ...options,
    method: "GET",
  });
};

export const getCreatorRetrieveQueryKey = (usernameIexact: string) => {
  return [`/api/creator/${usernameIexact}/`] as const;
};

export const getCreatorRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof creatorRetrieve>>,
  TError = unknown,
>(
  usernameIexact: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof creatorRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCreatorRetrieveQueryKey(usernameIexact);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof creatorRetrieve>>> = ({
    signal,
  }) => creatorRetrieve(usernameIexact, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: usernameIexact !== null && usernameIexact !== undefined,
    ...queryOptions,
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof creatorRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CreatorRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof creatorRetrieve>>
>;
export type CreatorRetrieveQueryError = unknown;

export function createCreatorRetrieve<
  TData = Awaited<ReturnType<typeof creatorRetrieve>>,
  TError = unknown,
>(
  usernameIexact: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof creatorRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCreatorRetrieveQueryOptions(usernameIexact, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
