//! **First contact, cold, against a real log, a real witness and a real relay.**
//!
//! This is the acceptance criterion for `WIRE.md` §12.6 and the end of §12.5's
//! *"dependency, flagged rather than invented"*. Two people who have never
//! spoken open a conversation and exchange messages both ways, and nothing in
//! the path is a fixture:
//!
//! | Piece | What it really is |
//! |---|---|
//! | The directory | `f2z_kt::LogService` — real `akd` trees, a real VRF, real Ed25519, real protobuf inclusion proofs, real epochs. |
//! | The witness | `f2z_witness::Witness` — it verifies the append-only proof before it cosigns, and the client's threshold is applied to what it produced. |
//! | The lookup | `KtClient::resolve` — §6.3's monotonicity rules, §8.3's threshold, the inclusion proof, the pin. The shipping client, unchanged. |
//! | The relay | `FakeRelay` over a **real `ws://127.0.0.1:0` socket**, driven through `connection::drive` and `engine::Relay`. |
//! | The key packages | Really generated by OpenMLS, really published with `PUBLISH_KEY_PACKAGES`, really claimed with `CLAIM_KEY_PACKAGE` behind a proof-of-work stamp. |
//! | The crypto | Real MLS under `MLS_256_XWING_CHACHA20POLY1305_SHA256_Ed25519`: a real `Welcome`, a real join, real `PrivateMessage`s. |
//!
//! # What "two independent instances" means here
//!
//! Two `MlsEngine`s over two separate stores, two separate `DeviceSigner`s, two
//! separate identities, two separate relay connections and two separate
//! `KtClient`s over two separate transports and pin stores. Nothing is shared
//! but the log, the witness and the relay — which is what they are supposed to
//! share. The bytes that cross between them are the bytes that would cross a
//! network: an encoded `DirectoryEntry` in the log's tree, a key package in the
//! relay's pool, a `Welcome`, and `PrivateMessage`s.
//!
//! They are not two *processes*. The plugin's `tests/two_instances_over_a_relay.rs`
//! is, and it drives the same `start_conversation` and `accept_contact_request`
//! over the same wire commands — what it cannot carry is the AGPL log and
//! witness, because `tauri-plugin-f2zmsg` is on the client side of
//! `rs/README.md`'s licence boundary. Between the two files every part of the
//! claim is exercised for real; neither file alone carries all of it, and this
//! is said here rather than implied.
//!
//! # The assertion that makes this more than "it did not panic"
//!
//! Alice never learns Bob's key package from Bob. She learns his *handle*, and
//! everything else is derived: the log proves his `DirectoryEntry`, the entry
//! names his `contact_addr`, the relay serves a package from the pool at that
//! address, and the package is authenticated **against the entry the log
//! proved**. `a_substituted_key_package_is_refused` is the same run with a
//! second, perfectly valid identity's package served in place of Bob's, and it
//! is refused — which is the property that makes putting key packages at an
//! untrusted relay sound at all.

// Test code, run on the host by a person reading the failure.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use std::sync::Arc;

use f2z_codec::Canonical as _;
use f2z_codec::types::{PublicKey, QueueAddress, RelayId};
use f2z_kt::LogService;
use f2z_kt::testing::{EntryBuilder, Harness, Identity, Key};
use f2z_kt_client::{ClientConfig, ClientError, KtClient, Transport};
use f2z_kt_core::entry::{DeviceCredential, DeviceCredentialTBS, DirectoryEntryTBS};
use f2z_kt_core::types::{Handle, KemPublicKey, label_field};
use f2z_kt_core::{ConfiguredWitness, WitnessSet, labels};
use f2z_msg_mls::{DeviceSigner, MlsEngine};
use f2z_msg_store::MemoryBackend;
use f2z_relay_proto::key::SigningKey;
use f2z_relay_testkit::client::Client;
use f2z_relay_testkit::fake::FakeRelay;
use f2z_witness::witness::{Outcome, Settings, Witness};

const NOW: u64 = 1_700_000_100_000;
const WITNESS_SEED: u8 = 0xc2;

// ---------------------------------------------------------------------------
// The socket to the log.
//
// The same shape `tests/acceptance.rs` uses and for the same reason: it encodes
// exactly what `f2z-kt`'s HTTP handlers encode, because it calls exactly what
// they call. Nothing here invents a response.
// ---------------------------------------------------------------------------

struct LogTransport {
    runtime: tokio::runtime::Runtime,
    log: Arc<LogService>,
}

/// A handle onto the transport, so two clients can share one socket to the log
/// the way two devices behind one NAT would.
///
/// A newtype rather than `impl Transport for Arc<LogTransport>`, because the
/// orphan rule forbids implementing this crate's trait for `alloc`'s type.
struct LogHandle(Arc<LogTransport>);

impl LogTransport {
    fn new(log: Arc<LogService>) -> Self {
        Self {
            runtime: tokio::runtime::Builder::new_multi_thread()
                .worker_threads(2)
                .enable_all()
                .build()
                .unwrap(),
            log,
        }
    }
}

impl Transport for LogHandle {
    fn latest_sth(&self) -> f2z_kt_client::Result<Vec<u8>> {
        let bundle = self
            .0
            .runtime
            .block_on(self.0.log.latest_bundle())
            .map_err(|error| ClientError::Unreachable(error.to_string()))?;
        Ok(bundle.encode_canonical().unwrap())
    }

    fn sth_at(&self, epoch: u64) -> f2z_kt_client::Result<Vec<u8>> {
        let bundle = self
            .0
            .runtime
            .block_on(self.0.log.bundle_at(epoch))
            .map_err(|error| ClientError::Unreachable(error.to_string()))?;
        Ok(bundle.encode_canonical().unwrap())
    }

    fn lookup(&self, request: &[u8]) -> f2z_kt_client::Result<Vec<u8>> {
        let decoded =
            f2z_codec::decode_canonical::<f2z_kt_core::api::LookupRequest>(request)?.into_value();
        decoded.validate()?;
        let response = self
            .0
            .runtime
            .block_on(self.0.log.lookup(&decoded.handle))
            .map_err(|error| ClientError::Unreachable(error.to_string()))?;
        Ok(response.encode_canonical().unwrap())
    }

    fn history(&self, request: &[u8]) -> f2z_kt_client::Result<Vec<u8>> {
        let decoded =
            f2z_codec::decode_canonical::<f2z_kt_core::api::HistoryRequest>(request)?.into_value();
        decoded.validate()?;
        let response = self
            .0
            .runtime
            .block_on(self.0.log.history(
                &decoded.handle,
                f2z_kt_core::verify::HistoryParams::Complete,
            ))
            .map_err(|error| ClientError::Unreachable(error.to_string()))?;
        Ok(response.encode_canonical().unwrap())
    }

    fn authority_policy(&self) -> f2z_kt_client::Result<Vec<u8>> {
        Err(ClientError::Unreachable(
            "this fixture serves no policy".to_owned(),
        ))
    }

    fn descriptor(&self) -> f2z_kt_client::Result<Vec<u8>> {
        Err(ClientError::Unreachable(
            "this fixture serves no descriptor".to_owned(),
        ))
    }
}

struct WitnessTransport(Arc<LogTransport>);

impl f2z_witness::Transport for WitnessTransport {
    fn latest_sth(&self) -> f2z_witness::Result<Vec<u8>> {
        let bundle = self
            .0
            .runtime
            .block_on(self.0.log.latest_bundle())
            .map_err(|error| f2z_witness::WitnessError::Transport(error.to_string()))?;
        Ok(bundle.encode_canonical().unwrap())
    }

    fn audit(&self, from: u64, to: u64) -> f2z_witness::Result<Vec<u8>> {
        let response = self
            .0
            .runtime
            .block_on(self.0.log.audit(from, to))
            .map_err(|error| f2z_witness::WitnessError::Transport(error.to_string()))?;
        Ok(response.encode_canonical().unwrap())
    }

    fn cosign(&self, cosignature: &[u8]) -> f2z_witness::Result<()> {
        let decoded = f2z_codec::decode_canonical::<f2z_kt_core::WitnessCosignature>(cosignature)
            .map_err(|error| f2z_witness::WitnessError::Transport(error.to_string()))?
            .into_value();
        self.0
            .runtime
            .block_on(self.0.log.accept_cosignature(&decoded))
            .map_err(|error| f2z_witness::WitnessError::Transport(error.to_string()))
    }
}

// ---------------------------------------------------------------------------
// One device: an identity, an MLS engine, a contact queue, and a published pool.
// ---------------------------------------------------------------------------

/// A device, built the way enrollment builds one.
///
/// The `DeviceCredential` is signed by the identity key that the directory entry
/// publishes, over the **real** MLS signing key — so the entry's `devices` set
/// and the credential inside every key package this device generates are the
/// same bytes. That is the whole precondition for §12.6.5's check to mean
/// anything.
struct Device {
    handle: String,
    identity: Identity,
    credential: DeviceCredential,
    mls: MlsEngine<MemoryBackend>,
    recv_key: SigningKey,
    recv_addr: QueueAddress,
    contact_addr: QueueAddress,
}

fn credential_for(identity: &Identity, handle: &str, device_pk: &[u8; 32]) -> DeviceCredential {
    let tbs = DeviceCredentialTBS {
        label: label_field(labels::LABEL_DEVICE_CREDENTIAL).unwrap(),
        identity_pk: identity.isk.public,
        handle: Handle::new(handle.as_bytes().to_vec()).unwrap(),
        device_pk: PublicKey::new(*device_pk),
        // Not read by MLS — the HPKE init key is the one inside the
        // `KeyPackage`, generated by OpenMLS. `KT.md` §4.1 requires only that it
        // is non-empty.
        device_kem_pk: KemPublicKey::new(vec![0x5a; 1216]).unwrap(),
        not_before_ms: NOW - 1_000_000,
        not_after_ms: NOW + 100_000_000,
    };
    let signature = identity.isk.sign(&tbs.signing_bytes().unwrap());
    DeviceCredential {
        credential: tbs,
        signature,
    }
}

impl Device {
    /// Cold start, in order: keys, then a contact queue on the relay, then MLS.
    ///
    /// The contact queue comes before the directory entry because the entry has
    /// to publish the address the relay issued (§12.2, §12.6). Nothing is
    /// pre-arranged.
    async fn enroll(handle: &str, identity_seed: u8, device_seed: u8, relay: &FakeRelay) -> Self {
        let identity = Identity::from_byte(identity_seed);
        let signer = DeviceSigner::from_private_key([device_seed; 32]);
        let credential = credential_for(&identity, handle, signer.public_key());

        let mls = MlsEngine::new(MemoryBackend::new(), signer, credential.clone(), NOW).unwrap();

        let recv_key = SigningKey::from_seed(&[device_seed.wrapping_add(0x10); 32]);
        let mut client = relay.client().await.unwrap();
        let created = client
            .create_contact_queue(&recv_key, 0, 0, None)
            .await
            .unwrap();

        Self {
            handle: handle.to_owned(),
            identity,
            credential,
            mls,
            recv_key,
            recv_addr: created.recv_addr,
            contact_addr: created.contact_addr,
        }
    }

    /// §12.6: publish a pool and one package of last resort.
    async fn publish_key_packages(&self, client: &mut Client, count: usize) -> u32 {
        let packages = self.mls.generate_key_packages(count, None).unwrap();
        let last_resort = self
            .mls
            .generate_last_resort_key_package(Some(2_592_000))
            .unwrap();
        let published = client
            .publish_key_packages(&self.recv_key, self.recv_addr, &packages, Some(last_resort))
            .await
            .unwrap();
        assert_eq!(published.has_last_resort, 1);
        published.pool_size
    }

    /// The `DirectoryEntry` this device submits: its real credential, and the
    /// real `contact_addr` the relay issued.
    fn entry(
        &self,
        log_id: f2z_kt_core::types::LogId,
        relay_url: &str,
    ) -> f2z_kt_core::entry::DirectoryEntry {
        EntryBuilder::first(log_id, &self.handle, &self.identity)
            .credential(self.credential.clone())
            .contact_endpoint(relay_url, RelayId::new([0x77; 32]), self.contact_addr)
            .same_key(&self.identity.dak)
    }
}

// ---------------------------------------------------------------------------
// The deployment.
// ---------------------------------------------------------------------------

struct Deployment {
    setup: tokio::runtime::Runtime,
    harness: Harness,
    transport: Arc<LogTransport>,
    witness: Witness,
}

impl Deployment {
    fn new(name: &str) -> Self {
        let setup = tokio::runtime::Runtime::new().unwrap();
        let harness = setup.block_on(Harness::vouched_with_witnesses(
            name,
            vec![Key::from_byte(WITNESS_SEED).public],
        ));
        setup.block_on(harness.log.publish_epoch(NOW)).unwrap();

        let transport = Arc::new(LogTransport::new(Arc::clone(&harness.log)));
        let dir = f2z_kt::testing::temp_dir(&format!("{name}-w"));
        let witness = Witness::new(
            Settings {
                log_id: harness.log_id,
                accepted_log_pk: harness.log.log_public_key(),
                state_path: dir.join("state.bin"),
                evidence_dir: dir.join("evidence"),
                max_audit_span: 64,
            },
            &[WITNESS_SEED; 32],
            Box::new(WitnessTransport(Arc::clone(&transport))),
        )
        .unwrap();

        Self {
            setup,
            harness,
            transport,
            witness,
        }
    }

    fn submit(&self, entry: &f2z_kt_core::entry::DirectoryEntry, identity: &Identity) {
        self.setup.block_on(async {
            self.harness
                .log
                .submit(&self.harness.envelope(entry, identity, NOW), NOW)
                .await
                .unwrap();
            self.harness.log.publish_epoch(NOW).await.unwrap();
        });
    }

    fn cosign(&mut self, now_ms: u64) {
        match self.witness.poll_once(now_ms).unwrap() {
            Outcome::Pinned { .. } | Outcome::Cosigned { .. } | Outcome::UpToDate { .. } => {}
            other => panic!("the witness refused to cosign an honest log: {other:?}"),
        }
    }

    /// A client that counts this deployment's witness, with `t = 1`.
    ///
    /// `dependent`, not `independent`: free2z would operate both the log and
    /// this witness, and §8.3 is explicit that such a set carries zero
    /// anti-equivocation value. Claiming independence here would make this a
    /// test of a property the deployment does not have.
    fn client(&self) -> KtClient<LogHandle> {
        let witnesses = WitnessSet::new(
            vec![ConfiguredWitness::dependent(self.witness.public_key())],
            1,
        )
        .unwrap();
        KtClient::bootstrap(
            LogHandle(Arc::clone(&self.transport)),
            ClientConfig {
                log_id: self.harness.log_id,
                accepted_log_pk: self.harness.log.log_public_key(),
                witnesses,
                reset_authority_pk: self.harness.reset_authority.public,
                reset_cooldown_seconds: 60,
            },
        )
        .unwrap()
    }
}

/// Resolve a handle through the real client and hand back the verified entry.
fn resolve(client: &mut KtClient<LogHandle>, handle: &str, now_ms: u64) -> DirectoryEntryTBS {
    let resolution = client
        .resolve(&Handle::new(handle.as_bytes().to_vec()).unwrap(), now_ms)
        .expect("an honest log, a cosigned root and a registered handle");
    let resolved = resolution
        .resolved()
        .expect("the handle is registered, and the log proved it");
    assert!(
        resolution.standing().threshold_met(),
        "the client must not have accepted a root without the threshold"
    );
    resolved.entry().entry.clone()
}

// ---------------------------------------------------------------------------
// The acceptance criterion.
// ---------------------------------------------------------------------------

#[test]
fn two_instances_open_a_conversation_from_nothing_but_a_handle() {
    let mut deployment = Deployment::new("first-contact");
    deployment.cosign(NOW);

    let relay_runtime = tokio::runtime::Runtime::new().unwrap();
    let (relay, server, url) = relay_runtime.block_on(async {
        let relay = FakeRelay::with_defaults().unwrap();
        let server = relay.listen_loopback().await.unwrap();
        let url = server.url();
        (relay, server, url)
    });

    // --- cold start: two devices that have never heard of each other --------
    let (alice, bob, mut alice_relay, mut bob_relay, pool) = relay_runtime.block_on(async {
        let alice = Device::enroll("alice", 0x11, 0xa1, &relay).await;
        let bob = Device::enroll("bob", 0x22, 0xb2, &relay).await;
        let mut alice_relay = relay.client().await.unwrap();
        let mut bob_relay = relay.client().await.unwrap();
        // §12.6: Bob publishes a pool before anyone has asked for one.
        let pool = bob.publish_key_packages(&mut bob_relay, 4).await;
        // Alice publishes hers too — first contact is symmetric, and a device
        // that only publishes when it is about to be contacted has published
        // too late.
        let _ = alice.publish_key_packages(&mut alice_relay, 4).await;
        (alice, bob, alice_relay, bob_relay, pool)
    });
    assert_eq!(pool, 4, "the relay holds what bob published");

    // --- both submit their directory entries, and the witness cosigns -------
    deployment.submit(
        &alice.entry(deployment.harness.log_id, &url),
        &alice.identity,
    );
    deployment.submit(&bob.entry(deployment.harness.log_id, &url), &bob.identity);
    deployment.cosign(NOW + 1);

    // --- step 1: alice resolves "bob" through the real client ---------------
    let mut alice_kt = deployment.client();
    let bob_entry = resolve(&mut alice_kt, "bob", NOW + 2);
    let published_contact_addr = QueueAddress::from_slice(
        bob_entry.contact_endpoints.as_slice()[0]
            .contact_addr
            .as_bytes(),
    )
    .unwrap();
    assert_eq!(
        published_contact_addr, bob.contact_addr,
        "the log published the address the relay actually issued"
    );

    // --- step 2: alice claims a key package from that address ---------------
    let claimed = relay_runtime.block_on(async {
        let pow = alice_relay
            .capabilities()
            .await
            .unwrap()
            .capabilities
            .claim_key_package_pow;
        alice_relay
            .claim_key_package(published_contact_addr, Some(pow))
            .await
            .unwrap()
    });
    assert_eq!(
        claimed.last_resort, 0,
        "bob's pool is not empty, so this is a single-use package"
    );

    // --- step 3: and authenticates it against the entry the log proved ------
    let verified = alice
        .mls
        .verify_key_package(claimed.key_package.as_slice(), &bob_entry, NOW + 3)
        .expect("bob's own package, vouched for by the entry bob's handle resolves to");
    assert!(!verified.last_resort());
    assert_eq!(
        verified.device_pk(),
        bob.credential.credential.device_pk.as_bytes()
    );

    // --- step 4: the group, the Welcome, and the conversation ---------------
    let mut alice_group = alice.mls.create_group(b"alice-bob").unwrap();
    let (_commit, welcome) = alice
        .mls
        .add_member(&mut alice_group, &verified, NOW + 4)
        .unwrap();

    // Bob's side. He resolves alice through his own client — §6.4 puts
    // accepting a first-contact Welcome in the same row as resolving a new
    // handle — and then joins.
    let mut bob_kt = deployment.client();
    let alice_entry = resolve(&mut bob_kt, "alice", NOW + 5);
    assert_eq!(
        alice_entry.identity_pk, alice.identity.isk.public,
        "bob confirmed whose Welcome this is against a cosigned root"
    );
    let mut bob_group = bob.mls.join_from_welcome(&welcome, NOW + 6).unwrap();

    assert_eq!(alice_group.group_id(), bob_group.group_id());
    assert_eq!(alice_group.epoch(), bob_group.epoch());

    // Both ways, through real MLS `PrivateMessage`s.
    let wire = alice.mls.send(&mut alice_group, b"hello, bob").unwrap();
    let received = bob
        .mls
        .receive(&mut bob_group, &wire, b"m1", NOW + 7)
        .unwrap();
    assert_eq!(received.payload(), Some(b"hello, bob".as_slice()));

    let reply = bob.mls.send(&mut bob_group, b"hello, alice").unwrap();
    let received = alice
        .mls
        .receive(&mut alice_group, &reply, b"m2", NOW + 8)
        .unwrap();
    assert_eq!(received.payload(), Some(b"hello, alice".as_slice()));

    // --- and the pool really was consumed -----------------------------------
    let second = relay_runtime.block_on(async {
        let pow = bob_relay
            .capabilities()
            .await
            .unwrap()
            .capabilities
            .claim_key_package_pow;
        bob_relay
            .claim_key_package(bob.contact_addr, Some(pow))
            .await
            .unwrap()
    });
    assert_ne!(
        second.key_package.as_slice(),
        claimed.key_package.as_slice(),
        "a claimed package must never be served twice: one init key, one Welcome"
    );

    relay_runtime.block_on(server.shutdown());
}

#[test]
fn a_key_package_whose_credential_is_not_the_directorys_is_refused() {
    // The MITM, with everything else real. A second, perfectly valid identity
    // publishes a perfectly valid pool at its own address; the relay serves one
    // of *its* packages when alice asks about bob. Every check that looks only
    // at the package passes — the signature, the leaf binding, the lifetime, the
    // ciphersuite. Only the directory entry stops it.
    let mut deployment = Deployment::new("first-contact-mitm");
    deployment.cosign(NOW);

    let relay_runtime = tokio::runtime::Runtime::new().unwrap();
    let (relay, server, url) = relay_runtime.block_on(async {
        let relay = FakeRelay::with_defaults().unwrap();
        let server = relay.listen_loopback().await.unwrap();
        let url = server.url();
        (relay, server, url)
    });

    let (alice, bob, mallory, substituted) = relay_runtime.block_on(async {
        let alice = Device::enroll("alice", 0x11, 0xa1, &relay).await;
        let bob = Device::enroll("bob", 0x22, 0xb2, &relay).await;
        let mallory = Device::enroll("mallory", 0x33, 0xc3, &relay).await;
        let mut client = relay.client().await.unwrap();
        let _ = bob.publish_key_packages(&mut client, 2).await;
        let _ = mallory.publish_key_packages(&mut client, 2).await;
        let pow = client
            .capabilities()
            .await
            .unwrap()
            .capabilities
            .claim_key_package_pow;
        // A real claim, from a real pool, at a real address — mallory's.
        let substituted = client
            .claim_key_package(mallory.contact_addr, Some(pow))
            .await
            .unwrap();
        (alice, bob, mallory, substituted)
    });

    deployment.submit(&bob.entry(deployment.harness.log_id, &url), &bob.identity);
    deployment.submit(
        &mallory.entry(deployment.harness.log_id, &url),
        &mallory.identity,
    );
    deployment.cosign(NOW + 1);

    let mut alice_kt = deployment.client();
    let bob_entry = resolve(&mut alice_kt, "bob", NOW + 2);

    let error = alice
        .mls
        .verify_key_package(substituted.key_package.as_slice(), &bob_entry, NOW + 3)
        .expect_err("a package from a different identity must never be usable for @bob");
    // §12.6.5 check 4: the credential does not verify under the entry's
    // `identity_pk`. Reported as a credential failure, never as a transport one
    // — §9 rule 5 forbids proceeding, and a retryable code would invite it.
    assert!(
        matches!(error, f2z_msg_mls::EngineError::Credential(_)),
        "{error:?}"
    );

    // And the honest package for the same handle still works, so the assertion
    // above is about the substitution rather than about the fixture.
    let honest = relay_runtime.block_on(async {
        let mut client = relay.client().await.unwrap();
        let pow = client
            .capabilities()
            .await
            .unwrap()
            .capabilities
            .claim_key_package_pow;
        client
            .claim_key_package(bob.contact_addr, Some(pow))
            .await
            .unwrap()
    });
    alice
        .mls
        .verify_key_package(honest.key_package.as_slice(), &bob_entry, NOW + 4)
        .expect("bob's own package verifies against bob's entry");

    relay_runtime.block_on(server.shutdown());
}

#[test]
fn an_exhausted_pool_falls_back_to_the_last_resort_package_and_then_refuses() {
    // §12.6.6's exhaustion behaviour, end to end and against the real relay: the
    // pool drains, the reusable package carries first contact, and a device that
    // published none is unreachable rather than crashed.
    let mut deployment = Deployment::new("first-contact-exhaustion");
    deployment.cosign(NOW);

    let relay_runtime = tokio::runtime::Runtime::new().unwrap();
    let (relay, server, url) = relay_runtime.block_on(async {
        let relay = FakeRelay::with_defaults().unwrap();
        let server = relay.listen_loopback().await.unwrap();
        let url = server.url();
        (relay, server, url)
    });

    let (alice, bob, spartan) = relay_runtime.block_on(async {
        let alice = Device::enroll("alice", 0x11, 0xa1, &relay).await;
        let bob = Device::enroll("bob", 0x22, 0xb2, &relay).await;
        let spartan = Device::enroll("spartan", 0x44, 0xd4, &relay).await;
        let mut client = relay.client().await.unwrap();
        // Exactly one single-use package, plus a last-resort one.
        let pool = bob.publish_key_packages(&mut client, 1).await;
        assert_eq!(pool, 1);
        // And a device that publishes a pool and **no** last-resort package —
        // §12.6.6's "MAY publish none, accepting unreachability over reuse".
        let packages = spartan.mls.generate_key_packages(1, None).unwrap();
        client
            .publish_key_packages(&spartan.recv_key, spartan.recv_addr, &packages, None)
            .await
            .unwrap();
        (alice, bob, spartan)
    });

    deployment.submit(&bob.entry(deployment.harness.log_id, &url), &bob.identity);
    deployment.submit(
        &spartan.entry(deployment.harness.log_id, &url),
        &spartan.identity,
    );
    deployment.cosign(NOW + 1);

    let mut alice_kt = deployment.client();
    let bob_entry = resolve(&mut alice_kt, "bob", NOW + 2);
    let spartan_entry = resolve(&mut alice_kt, "spartan", NOW + 2);

    relay_runtime.block_on(async {
        let mut client = relay.client().await.unwrap();
        let pow = client
            .capabilities()
            .await
            .unwrap()
            .capabilities
            .claim_key_package_pow;

        // One, and it is single-use.
        let first = client
            .claim_key_package(bob.contact_addr, Some(pow))
            .await
            .unwrap();
        assert_eq!(first.last_resort, 0);

        // Then twice more, and both are the same reusable package — which
        // verifies, and must, because refusing it would convert
        // `THREAT-MODEL.md` §4.12's documented trade into a failure to reach
        // somebody.
        let mut seen = Vec::new();
        for _ in 0..2 {
            let claimed = client
                .claim_key_package(bob.contact_addr, Some(pow))
                .await
                .unwrap();
            assert_eq!(claimed.last_resort, 1, "the relay says the pool is empty");
            let verified = alice
                .mls
                .verify_key_package(claimed.key_package.as_slice(), &bob_entry, NOW + 3)
                .expect("a last-resort package is a valid package from the right device");
            assert!(
                verified.last_resort(),
                "and it says so in its own signed extensions, not only in the relay's byte"
            );
            seen.push(claimed.key_package.as_slice().to_vec());
        }
        assert_eq!(seen[0], seen[1], "the last-resort package is not consumed");

        // The device that published no last-resort package: one claim, then
        // `ERR_UNAVAILABLE`. Not a panic, not an empty success.
        let only = client
            .claim_key_package(spartan.contact_addr, Some(pow))
            .await
            .unwrap();
        alice
            .mls
            .verify_key_package(only.key_package.as_slice(), &spartan_entry, NOW + 3)
            .expect("the one package spartan published");
        let error = client
            .claim_key_package(spartan.contact_addr, Some(pow))
            .await
            .expect_err("an exhausted pool with no last-resort package is a refusal");
        assert!(
            format!("{error}").contains("unavailable")
                || format!("{error:?}").contains("Unavailable"),
            "expected ERR_UNAVAILABLE, got {error:?}"
        );
    });

    relay_runtime.block_on(server.shutdown());
}
