/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  PaginatedzPageListList,
  PatchedzPageUpdate,
  ZPageDetail,
  ZPageUpdate,
  ZpageListParams
} from '../f2z.schemas';

import { customInstance } from '.././mutator';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * API endpoint that allows zpages to be viewed or edited.
This is the workhorse.
 */
export const zpageList = (
    params?: ZpageListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedzPageListList>(
      {url: `/api/zpage/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getZpageListQueryKey = (params?: ZpageListParams,) => {
    return [
    `/api/zpage/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getZpageListQueryOptions = <TData = Awaited<ReturnType<typeof zpageList>>, TError = unknown>(params?: ZpageListParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof zpageList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getZpageListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof zpageList>>> = ({ signal }) => zpageList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof zpageList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ZpageListQueryResult = NonNullable<Awaited<ReturnType<typeof zpageList>>>
export type ZpageListQueryError = unknown



export function createZpageList<TData = Awaited<ReturnType<typeof zpageList>>, TError = unknown>(
 params?: ZpageListParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof zpageList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getZpageListQueryOptions(params,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * API endpoint that allows zpages to be viewed or edited.
This is the workhorse.
 */
export const zpageCreate = (
    zPageUpdate: NonReadonly<ZPageUpdate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ZPageUpdate>(
      {url: `/api/zpage/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: zPageUpdate, signal
    },
      options);
    }
  


export const getZpageCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof zpageCreate>>, TError,{data: NonReadonly<ZPageUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof zpageCreate>>, TError,{data: NonReadonly<ZPageUpdate>}, TContext> => {

const mutationKey = ['zpageCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof zpageCreate>>, {data: NonReadonly<ZPageUpdate>}> = (props) => {
          const {data} = props ?? {};

          return  zpageCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ZpageCreateMutationResult = NonNullable<Awaited<ReturnType<typeof zpageCreate>>>
    export type ZpageCreateMutationBody = NonReadonly<ZPageUpdate>
    export type ZpageCreateMutationError = unknown

    export const createZpageCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof zpageCreate>>, TError,{data: NonReadonly<ZPageUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof zpageCreate>>,
        TError,
        {data: NonReadonly<ZPageUpdate>},
        TContext
      > => {

      const mutationOptions = getZpageCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const zpageVoteCreate = (
    free2zaddr: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/zpage/${free2zaddr}/vote/`, method: 'POST', signal
    },
      options);
    }
  


export const getZpageVoteCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof zpageVoteCreate>>, TError,{free2zaddr: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof zpageVoteCreate>>, TError,{free2zaddr: string}, TContext> => {

const mutationKey = ['zpageVoteCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof zpageVoteCreate>>, {free2zaddr: string}> = (props) => {
          const {free2zaddr} = props ?? {};

          return  zpageVoteCreate(free2zaddr,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ZpageVoteCreateMutationResult = NonNullable<Awaited<ReturnType<typeof zpageVoteCreate>>>
    
    export type ZpageVoteCreateMutationError = unknown

    export const createZpageVoteCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof zpageVoteCreate>>, TError,{free2zaddr: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof zpageVoteCreate>>,
        TError,
        {free2zaddr: string},
        TContext
      > => {

      const mutationOptions = getZpageVoteCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    /**
 * API endpoint that allows zpages to be viewed or edited.
This is the workhorse.
 */
export const zpageRetrieve = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ZPageDetail>(
      {url: `/api/zpage/${id}/`, method: 'GET', signal
    },
      options);
    }
  



export const getZpageRetrieveQueryKey = (id?: number,) => {
    return [
    `/api/zpage/${id}/`
    ] as const;
    }

    
export const getZpageRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof zpageRetrieve>>, TError = unknown>(id: number, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof zpageRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getZpageRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof zpageRetrieve>>> = ({ signal }) => zpageRetrieve(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof zpageRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type ZpageRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof zpageRetrieve>>>
export type ZpageRetrieveQueryError = unknown



export function createZpageRetrieve<TData = Awaited<ReturnType<typeof zpageRetrieve>>, TError = unknown>(
 id: number, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof zpageRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getZpageRetrieveQueryOptions(id,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * API endpoint that allows zpages to be viewed or edited.
This is the workhorse.
 */
export const zpageUpdate = (
    id: string,
    zPageUpdate: NonReadonly<ZPageUpdate>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<ZPageUpdate>(
      {url: `/api/zpage/${id}/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: zPageUpdate
    },
      options);
    }
  


export const getZpageUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof zpageUpdate>>, TError,{id: string;data: NonReadonly<ZPageUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof zpageUpdate>>, TError,{id: string;data: NonReadonly<ZPageUpdate>}, TContext> => {

const mutationKey = ['zpageUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof zpageUpdate>>, {id: string;data: NonReadonly<ZPageUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  zpageUpdate(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ZpageUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof zpageUpdate>>>
    export type ZpageUpdateMutationBody = NonReadonly<ZPageUpdate>
    export type ZpageUpdateMutationError = unknown

    export const createZpageUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof zpageUpdate>>, TError,{id: string;data: NonReadonly<ZPageUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof zpageUpdate>>,
        TError,
        {id: string;data: NonReadonly<ZPageUpdate>},
        TContext
      > => {

      const mutationOptions = getZpageUpdateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    /**
 * API endpoint that allows zpages to be viewed or edited.
This is the workhorse.
 */
export const zpagePartialUpdate = (
    id: string,
    patchedzPageUpdate: NonReadonly<PatchedzPageUpdate>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<ZPageUpdate>(
      {url: `/api/zpage/${id}/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedzPageUpdate
    },
      options);
    }
  


export const getZpagePartialUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof zpagePartialUpdate>>, TError,{id: string;data: NonReadonly<PatchedzPageUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof zpagePartialUpdate>>, TError,{id: string;data: NonReadonly<PatchedzPageUpdate>}, TContext> => {

const mutationKey = ['zpagePartialUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof zpagePartialUpdate>>, {id: string;data: NonReadonly<PatchedzPageUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  zpagePartialUpdate(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ZpagePartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof zpagePartialUpdate>>>
    export type ZpagePartialUpdateMutationBody = NonReadonly<PatchedzPageUpdate>
    export type ZpagePartialUpdateMutationError = unknown

    export const createZpagePartialUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof zpagePartialUpdate>>, TError,{id: string;data: NonReadonly<PatchedzPageUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof zpagePartialUpdate>>,
        TError,
        {id: string;data: NonReadonly<PatchedzPageUpdate>},
        TContext
      > => {

      const mutationOptions = getZpagePartialUpdateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    /**
 * API endpoint that allows zpages to be viewed or edited.
This is the workhorse.
 */
export const zpageDestroy = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/zpage/${id}/`, method: 'DELETE'
    },
      options);
    }
  


export const getZpageDestroyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof zpageDestroy>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof zpageDestroy>>, TError,{id: string}, TContext> => {

const mutationKey = ['zpageDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof zpageDestroy>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  zpageDestroy(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ZpageDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof zpageDestroy>>>
    
    export type ZpageDestroyMutationError = unknown

    export const createZpageDestroy = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof zpageDestroy>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof zpageDestroy>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getZpageDestroyMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const zpageFundCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/zpage/fund/`, method: 'POST', signal
    },
      options);
    }
  


export const getZpageFundCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof zpageFundCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof zpageFundCreate>>, TError,void, TContext> => {

const mutationKey = ['zpageFundCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof zpageFundCreate>>, void> = () => {
          

          return  zpageFundCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ZpageFundCreateMutationResult = NonNullable<Awaited<ReturnType<typeof zpageFundCreate>>>
    
    export type ZpageFundCreateMutationError = unknown

    export const createZpageFundCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof zpageFundCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof zpageFundCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getZpageFundCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    