/**
 * Generated by orval 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import { createMutation, createQuery } from "@tanstack/svelte-query";
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
} from "@tanstack/svelte-query";

import type {
  CreatorMeeting,
  DytePublicListParams,
  PaginatedCreatorMeetingList,
} from "../f2z.schemas";

import { customInstance } from ".././mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getDyteRetrieveUrl = (username: string, type: string) => {
  return `/api/dyte/${username}/${type}`;
};

/**
 * Returns number of participants in a meeting or 4XX if not live
 */
export const dyteRetrieve = async (
  username: string,
  type: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getDyteRetrieveUrl(username, type), {
    ...options,
    method: "GET",
  });
};

export const getDyteRetrieveQueryKey = (username: string, type: string) => {
  return [`/api/dyte/${username}/${type}`] as const;
};

export const getDyteRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof dyteRetrieve>>,
  TError = unknown,
>(
  username: string,
  type: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof dyteRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDyteRetrieveQueryKey(username, type);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dyteRetrieve>>> = ({
    signal,
  }) => dyteRetrieve(username, type, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled:
      username !== null &&
      username !== undefined &&
      type !== null &&
      type !== undefined,
    ...queryOptions,
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof dyteRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DyteRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof dyteRetrieve>>
>;
export type DyteRetrieveQueryError = unknown;

export function createDyteRetrieve<
  TData = Awaited<ReturnType<typeof dyteRetrieve>>,
  TError = unknown,
>(
  username: string,
  type: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof dyteRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDyteRetrieveQueryOptions(username, type, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getDyteCreateUrl = (username: string, type: string) => {
  return `/api/dyte/${username}/${type}`;
};

/**
 * Create/join _public_ meetings
 */
export const dyteCreate = async (
  username: string,
  type: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getDyteCreateUrl(username, type), {
    ...options,
    method: "POST",
  });
};

export const getDyteCreateMutationKey = () => ["dyteCreate"] as const;

export const getDyteCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof dyteCreate>>,
    TError,
    DyteCreateMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof dyteCreate>>,
  TError,
  DyteCreateMutationVariables,
  TContext
> => {
  const mutationKey = getDyteCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dyteCreate>>,
    DyteCreateMutationVariables
  > = (props) => {
    const { username, type } = props ?? {};

    return dyteCreate(username, type, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DyteCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof dyteCreate>>
>;

export type DyteCreateMutationError = unknown;
export type DyteCreateMutationVariables = { username: string; type: string };

export const createDyteCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof dyteCreate>>,
      TError,
      DyteCreateMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof dyteCreate>>,
  TError,
  DyteCreateMutationVariables,
  TContext
> => {
  return createMutation(getDyteCreateMutationOptions(options));
};
export const getDyteLiveStatusRetrieveUrl = (username: string) => {
  return `/api/dyte/${username}/live-status`;
};

export const dyteLiveStatusRetrieve = async (
  username: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getDyteLiveStatusRetrieveUrl(username), {
    ...options,
    method: "GET",
  });
};

export const getDyteLiveStatusRetrieveQueryKey = (username: string) => {
  return [`/api/dyte/${username}/live-status`] as const;
};

export const getDyteLiveStatusRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof dyteLiveStatusRetrieve>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof dyteLiveStatusRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDyteLiveStatusRetrieveQueryKey(username);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof dyteLiveStatusRetrieve>>
  > = ({ signal }) =>
    dyteLiveStatusRetrieve(username, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: username !== null && username !== undefined,
    ...queryOptions,
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof dyteLiveStatusRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DyteLiveStatusRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof dyteLiveStatusRetrieve>>
>;
export type DyteLiveStatusRetrieveQueryError = unknown;

export function createDyteLiveStatusRetrieve<
  TData = Awaited<ReturnType<typeof dyteLiveStatusRetrieve>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof dyteLiveStatusRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDyteLiveStatusRetrieveQueryOptions(username, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getDytePrivateRetrieveUrl = (username: string) => {
  return `/api/dyte/${username}/private`;
};

/**
 * GET will return the UUID for the currently logged in user's private meeting
 * POST will create a new private meeting for the currently logged in user,
 * if one does not already exist. Otherwise it will recycle the secret UUID
 * and return a new one
 *
 * Only for the creator to manage their own private meeting
 */
export const dytePrivateRetrieve = async (
  username: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getDytePrivateRetrieveUrl(username), {
    ...options,
    method: "GET",
  });
};

export const getDytePrivateRetrieveQueryKey = (username: string) => {
  return [`/api/dyte/${username}/private`] as const;
};

export const getDytePrivateRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof dytePrivateRetrieve>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof dytePrivateRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDytePrivateRetrieveQueryKey(username);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof dytePrivateRetrieve>>
  > = ({ signal }) =>
    dytePrivateRetrieve(username, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: username !== null && username !== undefined,
    ...queryOptions,
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof dytePrivateRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DytePrivateRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof dytePrivateRetrieve>>
>;
export type DytePrivateRetrieveQueryError = unknown;

export function createDytePrivateRetrieve<
  TData = Awaited<ReturnType<typeof dytePrivateRetrieve>>,
  TError = unknown,
>(
  username: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof dytePrivateRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDytePrivateRetrieveQueryOptions(username, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getDytePrivateCreateUrl = (username: string) => {
  return `/api/dyte/${username}/private`;
};

/**
 * GET will return the UUID for the currently logged in user's private meeting
 * POST will create a new private meeting for the currently logged in user,
 * if one does not already exist. Otherwise it will recycle the secret UUID
 * and return a new one
 *
 * Only for the creator to manage their own private meeting
 */
export const dytePrivateCreate = async (
  username: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getDytePrivateCreateUrl(username), {
    ...options,
    method: "POST",
  });
};

export const getDytePrivateCreateMutationKey = () =>
  ["dytePrivateCreate"] as const;

export const getDytePrivateCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof dytePrivateCreate>>,
    TError,
    DytePrivateCreateMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof dytePrivateCreate>>,
  TError,
  DytePrivateCreateMutationVariables,
  TContext
> => {
  const mutationKey = getDytePrivateCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dytePrivateCreate>>,
    DytePrivateCreateMutationVariables
  > = (props) => {
    const { username } = props ?? {};

    return dytePrivateCreate(username, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DytePrivateCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof dytePrivateCreate>>
>;

export type DytePrivateCreateMutationError = unknown;
export type DytePrivateCreateMutationVariables = { username: string };

export const createDytePrivateCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof dytePrivateCreate>>,
      TError,
      DytePrivateCreateMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof dytePrivateCreate>>,
  TError,
  DytePrivateCreateMutationVariables,
  TContext
> => {
  return createMutation(getDytePrivateCreateMutationOptions(options));
};
export const getDytePrivateCreate2Url = (username: string, secret: string) => {
  return `/api/dyte/${username}/private/${secret}`;
};

/**
 * Post will join the private meeting:
 *
 * For the creator, it will join the meeting as the host
 * For the participant, it will join the meeting as a participant
 */
export const dytePrivateCreate2 = async (
  username: string,
  secret: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getDytePrivateCreate2Url(username, secret), {
    ...options,
    method: "POST",
  });
};

export const getDytePrivateCreate2MutationKey = () =>
  ["dytePrivateCreate2"] as const;

export const getDytePrivateCreate2MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof dytePrivateCreate2>>,
    TError,
    DytePrivateCreate2MutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof dytePrivateCreate2>>,
  TError,
  DytePrivateCreate2MutationVariables,
  TContext
> => {
  const mutationKey = getDytePrivateCreate2MutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dytePrivateCreate2>>,
    DytePrivateCreate2MutationVariables
  > = (props) => {
    const { username, secret } = props ?? {};

    return dytePrivateCreate2(username, secret, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DytePrivateCreate2MutationResult = NonNullable<
  Awaited<ReturnType<typeof dytePrivateCreate2>>
>;

export type DytePrivateCreate2MutationError = unknown;
export type DytePrivateCreate2MutationVariables = {
  username: string;
  secret: string;
};

export const createDytePrivateCreate2 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof dytePrivateCreate2>>,
      TError,
      DytePrivateCreate2MutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof dytePrivateCreate2>>,
  TError,
  DytePrivateCreate2MutationVariables,
  TContext
> => {
  return createMutation(getDytePrivateCreate2MutationOptions(options));
};
export const getDytePublicListUrl = (params?: DytePublicListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/dyte/public/?${stringifiedParams}`
    : `/api/dyte/public/`;
};

export const dytePublicList = async (
  params?: DytePublicListParams,
  options?: Parameters<typeof customInstance>[1],
): Promise<PaginatedCreatorMeetingList> => {
  return customInstance<PaginatedCreatorMeetingList>(
    getDytePublicListUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getDytePublicListQueryKey = (params?: DytePublicListParams) => {
  return [`/api/dyte/public/`, ...(params ? [params] : [])] as const;
};

export const getDytePublicListQueryOptions = <
  TData = Awaited<ReturnType<typeof dytePublicList>>,
  TError = unknown,
>(
  params?: DytePublicListParams,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof dytePublicList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDytePublicListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dytePublicList>>> = ({
    signal,
  }) => dytePublicList(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof dytePublicList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DytePublicListQueryResult = NonNullable<
  Awaited<ReturnType<typeof dytePublicList>>
>;
export type DytePublicListQueryError = unknown;

export function createDytePublicList<
  TData = Awaited<ReturnType<typeof dytePublicList>>,
  TError = unknown,
>(
  params?: DytePublicListParams,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof dytePublicList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDytePublicListQueryOptions(params, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getDytePublicRetrieveUrl = (meetingId: string) => {
  return `/api/dyte/public/${meetingId}/`;
};

export const dytePublicRetrieve = async (
  meetingId: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<CreatorMeeting> => {
  return customInstance<CreatorMeeting>(getDytePublicRetrieveUrl(meetingId), {
    ...options,
    method: "GET",
  });
};

export const getDytePublicRetrieveQueryKey = (meetingId: string) => {
  return [`/api/dyte/public/${meetingId}/`] as const;
};

export const getDytePublicRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof dytePublicRetrieve>>,
  TError = unknown,
>(
  meetingId: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof dytePublicRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDytePublicRetrieveQueryKey(meetingId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof dytePublicRetrieve>>
  > = ({ signal }) =>
    dytePublicRetrieve(meetingId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: meetingId !== null && meetingId !== undefined,
    ...queryOptions,
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof dytePublicRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DytePublicRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof dytePublicRetrieve>>
>;
export type DytePublicRetrieveQueryError = unknown;

export function createDytePublicRetrieve<
  TData = Awaited<ReturnType<typeof dytePublicRetrieve>>,
  TError = unknown,
>(
  meetingId: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof dytePublicRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDytePublicRetrieveQueryOptions(meetingId, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getDyteWebhookCreateUrl = () => {
  return `/api/dyte/webhook`;
};

export const dyteWebhookCreate = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getDyteWebhookCreateUrl(), {
    ...options,
    method: "POST",
  });
};

export const getDyteWebhookCreateMutationKey = () =>
  ["dyteWebhookCreate"] as const;

export const getDyteWebhookCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof dyteWebhookCreate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof dyteWebhookCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getDyteWebhookCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dyteWebhookCreate>>,
    void
  > = () => {
    return dyteWebhookCreate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DyteWebhookCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof dyteWebhookCreate>>
>;

export type DyteWebhookCreateMutationError = unknown;

export const createDyteWebhookCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof dyteWebhookCreate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof dyteWebhookCreate>>,
  TError,
  void,
  TContext
> => {
  return createMutation(getDyteWebhookCreateMutationOptions(options));
};
export const getDyteWebhookRecordingStatusUpdateCreateUrl = () => {
  return `/api/dyte/webhook-recording-status-update/`;
};

/**
 * DEPRECATED
 */
export const dyteWebhookRecordingStatusUpdateCreate = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getDyteWebhookRecordingStatusUpdateCreateUrl(), {
    ...options,
    method: "POST",
  });
};

export const getDyteWebhookRecordingStatusUpdateCreateMutationKey = () =>
  ["dyteWebhookRecordingStatusUpdateCreate"] as const;

export const getDyteWebhookRecordingStatusUpdateCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof dyteWebhookRecordingStatusUpdateCreate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof dyteWebhookRecordingStatusUpdateCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getDyteWebhookRecordingStatusUpdateCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dyteWebhookRecordingStatusUpdateCreate>>,
    void
  > = () => {
    return dyteWebhookRecordingStatusUpdateCreate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DyteWebhookRecordingStatusUpdateCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof dyteWebhookRecordingStatusUpdateCreate>>
>;

export type DyteWebhookRecordingStatusUpdateCreateMutationError = unknown;

export const createDyteWebhookRecordingStatusUpdateCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof dyteWebhookRecordingStatusUpdateCreate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof dyteWebhookRecordingStatusUpdateCreate>>,
  TError,
  void,
  TContext
> => {
  return createMutation(
    getDyteWebhookRecordingStatusUpdateCreateMutationOptions(options),
  );
};
