/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  CreatorMeeting,
  DytePublicListParams,
  PaginatedCreatorMeetingList
} from '../f2z.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns number of participants in a meeting or 4XX if not live
 */
export const dyteRetrieve = (
    username: string,
    type: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/dyte/${username}/${type}`, method: 'GET', signal
    },
      options);
    }
  



export const getDyteRetrieveQueryKey = (username?: string,
    type?: string,) => {
    return [
    `/api/dyte/${username}/${type}`
    ] as const;
    }

    
export const getDyteRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof dyteRetrieve>>, TError = unknown>(username: string,
    type: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof dyteRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDyteRetrieveQueryKey(username,type);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dyteRetrieve>>> = ({ signal }) => dyteRetrieve(username,type, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(username && type), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof dyteRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type DyteRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof dyteRetrieve>>>
export type DyteRetrieveQueryError = unknown



export function createDyteRetrieve<TData = Awaited<ReturnType<typeof dyteRetrieve>>, TError = unknown>(
 username: string,
    type: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof dyteRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getDyteRetrieveQueryOptions(username,type,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create/join _public_ meetings
 */
export const dyteCreate = (
    username: string,
    type: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/dyte/${username}/${type}`, method: 'POST', signal
    },
      options);
    }
  


export const getDyteCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof dyteCreate>>, TError,{username: string;type: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof dyteCreate>>, TError,{username: string;type: string}, TContext> => {

const mutationKey = ['dyteCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dyteCreate>>, {username: string;type: string}> = (props) => {
          const {username,type} = props ?? {};

          return  dyteCreate(username,type,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DyteCreateMutationResult = NonNullable<Awaited<ReturnType<typeof dyteCreate>>>
    
    export type DyteCreateMutationError = unknown

    export const createDyteCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof dyteCreate>>, TError,{username: string;type: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof dyteCreate>>,
        TError,
        {username: string;type: string},
        TContext
      > => {

      const mutationOptions = getDyteCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const dyteLiveStatusRetrieve = (
    username: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/dyte/${username}/live-status`, method: 'GET', signal
    },
      options);
    }
  



export const getDyteLiveStatusRetrieveQueryKey = (username?: string,) => {
    return [
    `/api/dyte/${username}/live-status`
    ] as const;
    }

    
export const getDyteLiveStatusRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof dyteLiveStatusRetrieve>>, TError = unknown>(username: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof dyteLiveStatusRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDyteLiveStatusRetrieveQueryKey(username);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dyteLiveStatusRetrieve>>> = ({ signal }) => dyteLiveStatusRetrieve(username, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(username), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof dyteLiveStatusRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type DyteLiveStatusRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof dyteLiveStatusRetrieve>>>
export type DyteLiveStatusRetrieveQueryError = unknown



export function createDyteLiveStatusRetrieve<TData = Awaited<ReturnType<typeof dyteLiveStatusRetrieve>>, TError = unknown>(
 username: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof dyteLiveStatusRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getDyteLiveStatusRetrieveQueryOptions(username,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * GET will return the UUID for the currently logged in user's private meeting
POST will create a new private meeting for the currently logged in user,
if one does not already exist. Otherwise it will recycle the secret UUID
and return a new one

Only for the creator to manage their own private meeting
 */
export const dytePrivateRetrieve = (
    username: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/dyte/${username}/private`, method: 'GET', signal
    },
      options);
    }
  



export const getDytePrivateRetrieveQueryKey = (username?: string,) => {
    return [
    `/api/dyte/${username}/private`
    ] as const;
    }

    
export const getDytePrivateRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof dytePrivateRetrieve>>, TError = unknown>(username: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof dytePrivateRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDytePrivateRetrieveQueryKey(username);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dytePrivateRetrieve>>> = ({ signal }) => dytePrivateRetrieve(username, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(username), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof dytePrivateRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type DytePrivateRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof dytePrivateRetrieve>>>
export type DytePrivateRetrieveQueryError = unknown



export function createDytePrivateRetrieve<TData = Awaited<ReturnType<typeof dytePrivateRetrieve>>, TError = unknown>(
 username: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof dytePrivateRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getDytePrivateRetrieveQueryOptions(username,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * GET will return the UUID for the currently logged in user's private meeting
POST will create a new private meeting for the currently logged in user,
if one does not already exist. Otherwise it will recycle the secret UUID
and return a new one

Only for the creator to manage their own private meeting
 */
export const dytePrivateCreate = (
    username: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/dyte/${username}/private`, method: 'POST', signal
    },
      options);
    }
  


export const getDytePrivateCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof dytePrivateCreate>>, TError,{username: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof dytePrivateCreate>>, TError,{username: string}, TContext> => {

const mutationKey = ['dytePrivateCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dytePrivateCreate>>, {username: string}> = (props) => {
          const {username} = props ?? {};

          return  dytePrivateCreate(username,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DytePrivateCreateMutationResult = NonNullable<Awaited<ReturnType<typeof dytePrivateCreate>>>
    
    export type DytePrivateCreateMutationError = unknown

    export const createDytePrivateCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof dytePrivateCreate>>, TError,{username: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof dytePrivateCreate>>,
        TError,
        {username: string},
        TContext
      > => {

      const mutationOptions = getDytePrivateCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    /**
 * Post will join the private meeting:

For the creator, it will join the meeting as the host
For the participant, it will join the meeting as a participant
 */
export const dytePrivateCreate2 = (
    username: string,
    secret: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/dyte/${username}/private/${secret}`, method: 'POST', signal
    },
      options);
    }
  


export const getDytePrivateCreate2MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof dytePrivateCreate2>>, TError,{username: string;secret: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof dytePrivateCreate2>>, TError,{username: string;secret: string}, TContext> => {

const mutationKey = ['dytePrivateCreate2'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dytePrivateCreate2>>, {username: string;secret: string}> = (props) => {
          const {username,secret} = props ?? {};

          return  dytePrivateCreate2(username,secret,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DytePrivateCreate2MutationResult = NonNullable<Awaited<ReturnType<typeof dytePrivateCreate2>>>
    
    export type DytePrivateCreate2MutationError = unknown

    export const createDytePrivateCreate2 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof dytePrivateCreate2>>, TError,{username: string;secret: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof dytePrivateCreate2>>,
        TError,
        {username: string;secret: string},
        TContext
      > => {

      const mutationOptions = getDytePrivateCreate2MutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const dytePublicList = (
    params?: DytePublicListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedCreatorMeetingList>(
      {url: `/api/dyte/public/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getDytePublicListQueryKey = (params?: DytePublicListParams,) => {
    return [
    `/api/dyte/public/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getDytePublicListQueryOptions = <TData = Awaited<ReturnType<typeof dytePublicList>>, TError = unknown>(params?: DytePublicListParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof dytePublicList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDytePublicListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dytePublicList>>> = ({ signal }) => dytePublicList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof dytePublicList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type DytePublicListQueryResult = NonNullable<Awaited<ReturnType<typeof dytePublicList>>>
export type DytePublicListQueryError = unknown



export function createDytePublicList<TData = Awaited<ReturnType<typeof dytePublicList>>, TError = unknown>(
 params?: DytePublicListParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof dytePublicList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getDytePublicListQueryOptions(params,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const dytePublicRetrieve = (
    meetingId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreatorMeeting>(
      {url: `/api/dyte/public/${meetingId}/`, method: 'GET', signal
    },
      options);
    }
  



export const getDytePublicRetrieveQueryKey = (meetingId?: string,) => {
    return [
    `/api/dyte/public/${meetingId}/`
    ] as const;
    }

    
export const getDytePublicRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof dytePublicRetrieve>>, TError = unknown>(meetingId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof dytePublicRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDytePublicRetrieveQueryKey(meetingId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dytePublicRetrieve>>> = ({ signal }) => dytePublicRetrieve(meetingId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(meetingId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof dytePublicRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type DytePublicRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof dytePublicRetrieve>>>
export type DytePublicRetrieveQueryError = unknown



export function createDytePublicRetrieve<TData = Awaited<ReturnType<typeof dytePublicRetrieve>>, TError = unknown>(
 meetingId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof dytePublicRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getDytePublicRetrieveQueryOptions(meetingId,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const dyteWebhookCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/dyte/webhook`, method: 'POST', signal
    },
      options);
    }
  


export const getDyteWebhookCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof dyteWebhookCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof dyteWebhookCreate>>, TError,void, TContext> => {

const mutationKey = ['dyteWebhookCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dyteWebhookCreate>>, void> = () => {
          

          return  dyteWebhookCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DyteWebhookCreateMutationResult = NonNullable<Awaited<ReturnType<typeof dyteWebhookCreate>>>
    
    export type DyteWebhookCreateMutationError = unknown

    export const createDyteWebhookCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof dyteWebhookCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof dyteWebhookCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getDyteWebhookCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    /**
 * DEPRECATED
 */
export const dyteWebhookRecordingStatusUpdateCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/dyte/webhook-recording-status-update/`, method: 'POST', signal
    },
      options);
    }
  


export const getDyteWebhookRecordingStatusUpdateCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof dyteWebhookRecordingStatusUpdateCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof dyteWebhookRecordingStatusUpdateCreate>>, TError,void, TContext> => {

const mutationKey = ['dyteWebhookRecordingStatusUpdateCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dyteWebhookRecordingStatusUpdateCreate>>, void> = () => {
          

          return  dyteWebhookRecordingStatusUpdateCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DyteWebhookRecordingStatusUpdateCreateMutationResult = NonNullable<Awaited<ReturnType<typeof dyteWebhookRecordingStatusUpdateCreate>>>
    
    export type DyteWebhookRecordingStatusUpdateCreateMutationError = unknown

    export const createDyteWebhookRecordingStatusUpdateCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof dyteWebhookRecordingStatusUpdateCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof dyteWebhookRecordingStatusUpdateCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getDyteWebhookRecordingStatusUpdateCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    