/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  MutationFunction,
  QueryClient
} from '@tanstack/svelte-query';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const openaiImageCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/openai/image`, method: 'POST', signal
    },
      options);
    }
  


export const getOpenaiImageCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof openaiImageCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof openaiImageCreate>>, TError,void, TContext> => {

const mutationKey = ['openaiImageCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof openaiImageCreate>>, void> = () => {
          

          return  openaiImageCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OpenaiImageCreateMutationResult = NonNullable<Awaited<ReturnType<typeof openaiImageCreate>>>
    
    export type OpenaiImageCreateMutationError = unknown

    export const createOpenaiImageCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof openaiImageCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof openaiImageCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getOpenaiImageCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const openaiPromptCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/openai/prompt`, method: 'POST', signal
    },
      options);
    }
  


export const getOpenaiPromptCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof openaiPromptCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof openaiPromptCreate>>, TError,void, TContext> => {

const mutationKey = ['openaiPromptCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof openaiPromptCreate>>, void> = () => {
          

          return  openaiPromptCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OpenaiPromptCreateMutationResult = NonNullable<Awaited<ReturnType<typeof openaiPromptCreate>>>
    
    export type OpenaiPromptCreateMutationError = unknown

    export const createOpenaiPromptCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof openaiPromptCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof openaiPromptCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getOpenaiPromptCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    