/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  PaginatedTransactionList,
  StripeTransactionsListParams,
  Transaction
} from '../f2z.schemas';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const stripeCreateCheckoutSessionCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/stripe/create-checkout-session/`, method: 'POST', signal
    },
      options);
    }
  


export const getStripeCreateCheckoutSessionCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof stripeCreateCheckoutSessionCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof stripeCreateCheckoutSessionCreate>>, TError,void, TContext> => {

const mutationKey = ['stripeCreateCheckoutSessionCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stripeCreateCheckoutSessionCreate>>, void> = () => {
          

          return  stripeCreateCheckoutSessionCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StripeCreateCheckoutSessionCreateMutationResult = NonNullable<Awaited<ReturnType<typeof stripeCreateCheckoutSessionCreate>>>
    
    export type StripeCreateCheckoutSessionCreateMutationError = unknown

    export const createStripeCreateCheckoutSessionCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof stripeCreateCheckoutSessionCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof stripeCreateCheckoutSessionCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStripeCreateCheckoutSessionCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const stripeTransactionsList = (
    params?: StripeTransactionsListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedTransactionList>(
      {url: `/api/stripe/transactions/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getStripeTransactionsListQueryKey = (params?: StripeTransactionsListParams,) => {
    return [
    `/api/stripe/transactions/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStripeTransactionsListQueryOptions = <TData = Awaited<ReturnType<typeof stripeTransactionsList>>, TError = unknown>(params?: StripeTransactionsListParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof stripeTransactionsList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStripeTransactionsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof stripeTransactionsList>>> = ({ signal }) => stripeTransactionsList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof stripeTransactionsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type StripeTransactionsListQueryResult = NonNullable<Awaited<ReturnType<typeof stripeTransactionsList>>>
export type StripeTransactionsListQueryError = unknown



export function createStripeTransactionsList<TData = Awaited<ReturnType<typeof stripeTransactionsList>>, TError = unknown>(
 params?: StripeTransactionsListParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof stripeTransactionsList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getStripeTransactionsListQueryOptions(params,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const stripeTransactionsRetrieve = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Transaction>(
      {url: `/api/stripe/transactions/${id}/`, method: 'GET', signal
    },
      options);
    }
  



export const getStripeTransactionsRetrieveQueryKey = (id?: number,) => {
    return [
    `/api/stripe/transactions/${id}/`
    ] as const;
    }

    
export const getStripeTransactionsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof stripeTransactionsRetrieve>>, TError = unknown>(id: number, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof stripeTransactionsRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStripeTransactionsRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof stripeTransactionsRetrieve>>> = ({ signal }) => stripeTransactionsRetrieve(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof stripeTransactionsRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type StripeTransactionsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof stripeTransactionsRetrieve>>>
export type StripeTransactionsRetrieveQueryError = unknown



export function createStripeTransactionsRetrieve<TData = Awaited<ReturnType<typeof stripeTransactionsRetrieve>>, TError = unknown>(
 id: number, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof stripeTransactionsRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getStripeTransactionsRetrieveQueryOptions(id,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




