/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  CreatorLogin,
  PasswordChange,
  PasswordReset,
  PasswordResetConfirm,
  RestAuthDetail,
  Token,
  UserDetails
} from '../f2z.schemas';

import { customInstance } from '.././mutator';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Check the credentials and return the REST Token
if the credentials are valid and authenticated.
Calls Django Auth login method to register User ID
in Django session framework

Accept the following POST parameters: username, password
Return the REST Framework Token Object's key.
 */
export const authLoginCreate = (
    creatorLogin: CreatorLogin,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Token>(
      {url: `/api/auth/login/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: creatorLogin, signal
    },
      options);
    }
  


export const getAuthLoginCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authLoginCreate>>, TError,{data: CreatorLogin}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof authLoginCreate>>, TError,{data: CreatorLogin}, TContext> => {

const mutationKey = ['authLoginCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLoginCreate>>, {data: CreatorLogin}> = (props) => {
          const {data} = props ?? {};

          return  authLoginCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthLoginCreateMutationResult = NonNullable<Awaited<ReturnType<typeof authLoginCreate>>>
    export type AuthLoginCreateMutationBody = CreatorLogin
    export type AuthLoginCreateMutationError = unknown

    export const createAuthLoginCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authLoginCreate>>, TError,{data: CreatorLogin}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authLoginCreate>>,
        TError,
        {data: CreatorLogin},
        TContext
      > => {

      const mutationOptions = getAuthLoginCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    /**
 * Calls Django logout method and delete the Token object
assigned to the current User object.

Accepts/Returns nothing.
 */
export const authLogoutCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RestAuthDetail>(
      {url: `/api/auth/logout/`, method: 'POST', signal
    },
      options);
    }
  


export const getAuthLogoutCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authLogoutCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof authLogoutCreate>>, TError,void, TContext> => {

const mutationKey = ['authLogoutCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogoutCreate>>, void> = () => {
          

          return  authLogoutCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthLogoutCreateMutationResult = NonNullable<Awaited<ReturnType<typeof authLogoutCreate>>>
    
    export type AuthLogoutCreateMutationError = unknown

    export const createAuthLogoutCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authLogoutCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authLogoutCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthLogoutCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    /**
 * Calls Django Auth SetPasswordForm save method.

Accepts the following POST parameters: new_password1, new_password2
Returns the success/fail message.
 */
export const authPasswordChangeCreate = (
    passwordChange: PasswordChange,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RestAuthDetail>(
      {url: `/api/auth/password/change/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordChange, signal
    },
      options);
    }
  


export const getAuthPasswordChangeCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authPasswordChangeCreate>>, TError,{data: PasswordChange}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof authPasswordChangeCreate>>, TError,{data: PasswordChange}, TContext> => {

const mutationKey = ['authPasswordChangeCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authPasswordChangeCreate>>, {data: PasswordChange}> = (props) => {
          const {data} = props ?? {};

          return  authPasswordChangeCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthPasswordChangeCreateMutationResult = NonNullable<Awaited<ReturnType<typeof authPasswordChangeCreate>>>
    export type AuthPasswordChangeCreateMutationBody = PasswordChange
    export type AuthPasswordChangeCreateMutationError = unknown

    export const createAuthPasswordChangeCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authPasswordChangeCreate>>, TError,{data: PasswordChange}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authPasswordChangeCreate>>,
        TError,
        {data: PasswordChange},
        TContext
      > => {

      const mutationOptions = getAuthPasswordChangeCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    /**
 * Calls Django Auth PasswordResetForm save method.

Accepts the following POST parameters: email
Returns the success/fail message.
 */
export const authPasswordResetCreate = (
    passwordReset: PasswordReset,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RestAuthDetail>(
      {url: `/api/auth/password/reset/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordReset, signal
    },
      options);
    }
  


export const getAuthPasswordResetCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authPasswordResetCreate>>, TError,{data: PasswordReset}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof authPasswordResetCreate>>, TError,{data: PasswordReset}, TContext> => {

const mutationKey = ['authPasswordResetCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authPasswordResetCreate>>, {data: PasswordReset}> = (props) => {
          const {data} = props ?? {};

          return  authPasswordResetCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthPasswordResetCreateMutationResult = NonNullable<Awaited<ReturnType<typeof authPasswordResetCreate>>>
    export type AuthPasswordResetCreateMutationBody = PasswordReset
    export type AuthPasswordResetCreateMutationError = unknown

    export const createAuthPasswordResetCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authPasswordResetCreate>>, TError,{data: PasswordReset}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authPasswordResetCreate>>,
        TError,
        {data: PasswordReset},
        TContext
      > => {

      const mutationOptions = getAuthPasswordResetCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    /**
 * Password reset e-mail link is confirmed, therefore
this resets the user's password.

Accepts the following POST parameters: token, uid,
    new_password1, new_password2
Returns the success/fail message.
 */
export const authPasswordResetConfirmCreate = (
    passwordResetConfirm: PasswordResetConfirm,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RestAuthDetail>(
      {url: `/api/auth/password/reset/confirm/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordResetConfirm, signal
    },
      options);
    }
  


export const getAuthPasswordResetConfirmCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authPasswordResetConfirmCreate>>, TError,{data: PasswordResetConfirm}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof authPasswordResetConfirmCreate>>, TError,{data: PasswordResetConfirm}, TContext> => {

const mutationKey = ['authPasswordResetConfirmCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authPasswordResetConfirmCreate>>, {data: PasswordResetConfirm}> = (props) => {
          const {data} = props ?? {};

          return  authPasswordResetConfirmCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthPasswordResetConfirmCreateMutationResult = NonNullable<Awaited<ReturnType<typeof authPasswordResetConfirmCreate>>>
    export type AuthPasswordResetConfirmCreateMutationBody = PasswordResetConfirm
    export type AuthPasswordResetConfirmCreateMutationError = unknown

    export const createAuthPasswordResetConfirmCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authPasswordResetConfirmCreate>>, TError,{data: PasswordResetConfirm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authPasswordResetConfirmCreate>>,
        TError,
        {data: PasswordResetConfirm},
        TContext
      > => {

      const mutationOptions = getAuthPasswordResetConfirmCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    /**
 * This is only for the owner
 */
export const authUserRetrieve = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/auth/user/`, method: 'GET', signal
    },
      options);
    }
  



export const getAuthUserRetrieveQueryKey = () => {
    return [
    `/api/auth/user/`
    ] as const;
    }

    
export const getAuthUserRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof authUserRetrieve>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof authUserRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthUserRetrieveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authUserRetrieve>>> = ({ signal }) => authUserRetrieve(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof authUserRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type AuthUserRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof authUserRetrieve>>>
export type AuthUserRetrieveQueryError = unknown



export function createAuthUserRetrieve<TData = Awaited<ReturnType<typeof authUserRetrieve>>, TError = unknown>(
  options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof authUserRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getAuthUserRetrieveQueryOptions(options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * This is only for the owner
 */
export const authUserUpdate = (
    userDetails: NonReadonly<UserDetails>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UserDetails>(
      {url: `/api/auth/user/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userDetails
    },
      options);
    }
  


export const getAuthUserUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authUserUpdate>>, TError,{data: NonReadonly<UserDetails>}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof authUserUpdate>>, TError,{data: NonReadonly<UserDetails>}, TContext> => {

const mutationKey = ['authUserUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authUserUpdate>>, {data: NonReadonly<UserDetails>}> = (props) => {
          const {data} = props ?? {};

          return  authUserUpdate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthUserUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof authUserUpdate>>>
    export type AuthUserUpdateMutationBody = NonReadonly<UserDetails>
    export type AuthUserUpdateMutationError = unknown

    export const createAuthUserUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authUserUpdate>>, TError,{data: NonReadonly<UserDetails>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authUserUpdate>>,
        TError,
        {data: NonReadonly<UserDetails>},
        TContext
      > => {

      const mutationOptions = getAuthUserUpdateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    /**
 * This is only for the owner
 */
export const authUserPartialUpdate = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/auth/user/`, method: 'PATCH'
    },
      options);
    }
  


export const getAuthUserPartialUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authUserPartialUpdate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof authUserPartialUpdate>>, TError,void, TContext> => {

const mutationKey = ['authUserPartialUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authUserPartialUpdate>>, void> = () => {
          

          return  authUserPartialUpdate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthUserPartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof authUserPartialUpdate>>>
    
    export type AuthUserPartialUpdateMutationError = unknown

    export const createAuthUserPartialUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof authUserPartialUpdate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof authUserPartialUpdate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthUserPartialUpdateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    