//! Per-device keys — `ARCHITECTURE.md` §4.2's third table.
//!
//! > Per-device, generated on-device from the OS CSPRNG, **never seed-derived,
//! > never exported**.
//!
//! That sentence is the whole module. §4.1 gives the reason: identity keys are
//! seed-derived so restoring the wallet restores the identity, and device keys
//! are *not*, "so that seed compromise does not retroactively yield every
//! device's MLS state." There is deliberately **no function anywhere in this
//! crate** that produces a [`DeviceSignatureKey`] or a [`QueueKey`] from a seed,
//! from an [`crate::node::ExtendedNode`], or from anything else deterministic.
//! `tests/no_seed_derived_device_keys.rs` asserts that two derivations from the
//! same seed produce different device keys, which is the observable form of it.
//!
//! # The CSPRNG boundary, and why it is a parameter
//!
//! This crate is `no_std`, does no I/O, and compiles to
//! `wasm32-unknown-unknown`. It therefore *cannot* read an OS generator, and
//! pretending otherwise would mean either a platform shim in a crate that has
//! promised not to have one, or a "deterministic for now" placeholder, which is
//! the worst possible thing to put in a file called `device.rs`.
//!
//! So the generator is a parameter, typed [`rand_core::CryptoRng`]. That trait
//! is a marker with no implementation of its own: implementing it is the
//! caller's assertion that the source is cryptographically secure. On the two
//! platforms ADR 0001 names, the caller is `getrandom`'s `SysRng` — `getrandom`
//! on the desktop, `crypto.getRandomValues` in the browser.
//!
//! **A caller that hands these functions a seeded PRNG has produced a
//! seed-derived device key and defeated §4.1.** That is stated here because a
//! type cannot state it: `CryptoRng` is a promise, not a proof.
//!
//! # What is *not* here: the `DeviceInitKey`
//!
//! §4.2's third table has three rows and this module implements two of them.
//! The missing one is `DeviceInitKey` / the KeyPackage keys, which §4.2 types
//! as **X-Wing hybrid (X25519 + ML-KEM-768)** and §5.2 fixes as the MLS
//! ciphersuite's HPKE init key.
//!
//! It is absent on purpose rather than forgotten. §3.1 decides that the X-Wing
//! implementation is Cryspen's libcrux, reached through OpenMLS's crypto
//! provider — `openmls_rust_crypto` does not implement X-Wing at all — so the
//! keypair is generated by the MLS layer, as part of a `KeyPackage`, using the
//! same provider that will later decapsulate with it. Generating it here would
//! mean a second X-Wing implementation in the tree for the sake of tidiness in
//! a table, and a hybrid KEM whose combiner is written twice is exactly the
//! implementation-divergence class ADR 0001 exists to avoid.
//!
//! What this crate needs from that key is its **public** half, and it takes it
//! as opaque bytes: `KT.md` §4.1 declares `device_kem_pk` as
//! `opaque <1..2^16-1>` and validates only its length, because an MLS peer
//! validating a `LeafNode` is the thing that interprets it. See
//! [`crate::credential`].

use ed25519_dalek::{Signer as _, SigningKey};
use f2z_codec::types::{PublicKey, Signature};
use rand_core::CryptoRng;
use zeroize::Zeroizing;

/// Draw 32 bytes from the caller's CSPRNG into a wrapper that clears them.
///
/// The bytes exist only long enough to become an `ed25519_dalek::SigningKey`,
/// which is itself `ZeroizeOnDrop`.
fn secret_from<R: CryptoRng + ?Sized>(rng: &mut R) -> Zeroizing<[u8; 32]> {
    let mut secret = Zeroizing::new([0u8; 32]);
    rng.fill_bytes(secret.as_mut_slice());
    secret
}

/// Declare a per-device Ed25519 key: redacting `Debug`, zeroization through
/// dalek's `SigningKey`, and generation **only** from a `CryptoRng`.
macro_rules! device_key {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        ///
        /// # Zeroization
        ///
        /// The secret lives in an [`ed25519_dalek::SigningKey`], which is
        /// `ZeroizeOnDrop`. See the crate-level note for the WASM caveat.
        pub struct $name(SigningKey);

        impl $name {
            /// Generate this key from the OS CSPRNG.
            ///
            /// There is no `from_seed`, and adding one would be a defect: see
            /// the module note.
            pub fn generate<R: CryptoRng + ?Sized>(rng: &mut R) -> Self {
                Self(SigningKey::from_bytes(&secret_from(rng)))
            }

            /// The public key, as the wire and the directory carry it.
            #[must_use]
            pub fn public(&self) -> PublicKey {
                PublicKey::new(self.0.verifying_key().to_bytes())
            }
        }

        /// Hand-written, never derived — `f2z-codec`'s decimal-dump trap.
        impl core::fmt::Debug for $name {
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                f.write_str(concat!(stringify!($name), "(<redacted>)"))
            }
        }
    };
}

device_key!(
    /// `DeviceSignatureKey` (DSK) — the MLS leaf `signature_key`
    /// (RFC 9420 §7.2), bound to the account by a `DeviceCredential`.
    ///
    /// It signs MLS handshake and application framing, which is why it is
    /// **not** the [`crate::account::IdentitySigningKey`]: §4.1 requires that
    /// the key which signs message content and the key a peer pins as an
    /// identity are different keys.
    DeviceSignatureKey
);

device_key!(
    /// `QueueKey_{q}` — one per relay queue, authorizing send or receive on it
    /// (`ARCHITECTURE.md` §6.2, `WIRE.md` §5.1).
    ///
    /// One key per queue rather than one key for all of them: a queue key is
    /// presented to a relay, so sharing one across queues would let a relay
    /// link them, which is the metadata property the queue design exists to
    /// provide. `ADR 0009` fixes the addressing that goes with it.
    QueueKey
);

impl DeviceSignatureKey {
    /// Sign MLS framing with the device's leaf signature key.
    ///
    /// The bytes are MLS's — RFC 9420 fixes what a `FramedContentTBS` is — so
    /// this method does no framing of its own. It exists so the *key choice* is
    /// explicit: message content is signed by the device key and never by the
    /// identity key (§4.1).
    #[must_use]
    pub fn sign_mls_content(&self, framed_content_tbs: &[u8]) -> Signature {
        Signature::new(self.0.sign(framed_content_tbs).to_bytes())
    }
}

impl QueueKey {
    /// Sign a relay command transcript (`WIRE.md` §5.1).
    ///
    /// The transcript is built by `f2z-codec`'s `transcript` module, which is
    /// the only place the bytes a relay checks are constructed.
    #[must_use]
    pub fn sign_queue_command(&self, transcript: &[u8]) -> Signature {
        Signature::new(self.0.sign(transcript).to_bytes())
    }
}

/// The per-device key set, generated together from one CSPRNG.
///
/// The `DeviceInitKey` is absent by design; see the module note.
pub struct DeviceKeys {
    /// The MLS leaf `signature_key`.
    pub signature: DeviceSignatureKey,
}

/// Hand-written so that logging the bundle logs nothing.
impl core::fmt::Debug for DeviceKeys {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("DeviceKeys(<redacted>)")
    }
}

impl DeviceKeys {
    /// Generate a device's keys from the OS CSPRNG.
    pub fn generate<R: CryptoRng + ?Sized>(rng: &mut R) -> Self {
        Self {
            signature: DeviceSignatureKey::generate(rng),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::format;
    use alloc::vec::Vec;

    /// A counter, not a CSPRNG. It exists so the tests are reproducible and it
    /// is `#[cfg(test)]`, which is the only place a `CryptoRng` may be a lie.
    struct CountingRng(u64);

    impl rand_core::TryRng for CountingRng {
        type Error = core::convert::Infallible;

        fn try_next_u32(&mut self) -> Result<u32, Self::Error> {
            Ok(self.try_next_u64()? as u32)
        }

        fn try_next_u64(&mut self) -> Result<u64, Self::Error> {
            self.0 = self.0.wrapping_add(0x9e37_79b9_7f4a_7c15);
            Ok(self.0)
        }

        fn try_fill_bytes(&mut self, dst: &mut [u8]) -> Result<(), Self::Error> {
            for chunk in dst.chunks_mut(8) {
                let word = self.try_next_u64()?.to_le_bytes();
                let len = chunk.len();
                if let (Some(target), Some(source)) = (chunk.get_mut(..len), word.get(..len)) {
                    target.copy_from_slice(source);
                }
            }
            Ok(())
        }
    }

    impl rand_core::TryCryptoRng for CountingRng {}

    #[test]
    fn two_devices_from_one_generator_are_different_devices() {
        let mut rng = CountingRng(0);
        let first = DeviceSignatureKey::generate(&mut rng);
        let second = DeviceSignatureKey::generate(&mut rng);
        assert_ne!(first.public(), second.public());
    }

    #[test]
    fn queue_keys_do_not_repeat() {
        let mut rng = CountingRng(7);
        let queues: Vec<PublicKey> = (0..8)
            .map(|_| QueueKey::generate(&mut rng).public())
            .collect();
        for (i, a) in queues.iter().enumerate() {
            for (j, b) in queues.iter().enumerate() {
                assert!(i == j || a != b, "two queues share a key");
            }
        }
    }

    #[test]
    fn a_device_key_debug_is_redacted_in_hex_and_in_decimal() {
        let mut rng = CountingRng(1);
        let keys = DeviceKeys::generate(&mut rng);
        for rendered in [format!("{:?}", keys.signature), format!("{keys:?}")] {
            assert!(rendered.contains("<redacted>"), "{rendered}");
            for byte in keys.signature.public().as_bytes() {
                assert!(
                    !rendered.contains(&format!("{byte}")),
                    "decimal leak: {rendered}"
                );
            }
        }
    }

    #[test]
    fn a_signature_is_over_the_bytes_it_was_given() {
        // Not a verification test — this crate does not verify — but a
        // signature over a different message must be different bytes, which is
        // enough to catch a method signing a constant.
        let mut rng = CountingRng(2);
        let key = DeviceSignatureKey::generate(&mut rng);
        assert_ne!(
            key.sign_mls_content(b"one message"),
            key.sign_mls_content(b"another message")
        );
    }
}
