//! The free2z messaging key hierarchy — [`docs/e2ee/ARCHITECTURE.md`] §4.1,
//! §4.2 and §4.3, and nothing else.
//!
//! One BIP-39 seed in; a restorable messaging identity, a set of per-device
//! keys that are deliberately *not* restorable, and a signed `DeviceCredential`
//! binding the two, out.
//!
//! ```text
//! mnemonic ──► S ──► Sapling / Orchard trees            (wallet; never touched here)
//!               └──► MSK ──► account_node ──► ISK, CSK, DirectoryAuthKey, BackupWrapKey
//!                                               │
//!                                               └─ signs ─► DeviceCredential
//!                                                              ▲
//!                      OS CSPRNG ──► DSK, DeviceInitKey, QueueKeys (per device)
//! ```
//!
//! # The five properties this crate is required to keep
//!
//! Each has a test, and each is a thing an auditor checks first.
//!
//! 1. **No Zcash spending or viewing key is reachable from any messaging key
//!    path.** [ADR 0006] calls this non-negotiable and §4.1 calls it bedrock:
//!    different curves, and more fundamentally key separation. The messaging
//!    tree is rooted at its own BLAKE2b personalization
//!    (`"Free2zMsg_MSTRv1"`), so it is not the same hash function as ZIP 32's
//!    trees at any level — they cannot collide even at identical indices.
//!    `tests/zcash_separation.rs` asserts it against a ZIP-32 derivation
//!    computed independently in the test, which is #311's acceptance criterion
//!    spelled out.
//! 2. **Domain separation everywhere.** Every derivation is a keyed hash under
//!    a distinct versioned label, and no key is used for two purposes. See
//!    [`labels`], and note that `scripts/check-hash-domain-labels.mjs` holds
//!    this crate's labels against every other `free2z/` label in the tree.
//! 3. **Identity is restorable from the mnemonic; device keys are not.**
//!    [`account::AccountKeys::from_seed`] exists; there is no
//!    `DeviceSignatureKey::from_seed`, and there will not be one. Seed
//!    compromise must not retroactively yield every device's MLS state
//!    ([ADR 0002]).
//! 4. **Non-repudiation and deniable-style authentication never share a key.**
//!    [`account::CeremonySigningKey`] signs FROST/DKG payloads and nothing
//!    else; [`account::IdentitySigningKey`] never signs message content. No key
//!    type in this crate exposes a general `sign(&[u8])` — see [`account`]'s
//!    table.
//! 5. **Redacting `Debug` on every key type.** Following `f2z-codec`'s pattern
//!    *and its documented trap*: `tls_codec`'s byte vectors derive `Debug` and
//!    print a full **decimal** byte list containing no hex at all, so a
//!    hex-only redaction test passes while everything leaks.
//!    `tests/redaction.rs` checks the decimal spelling too.
//!
//! # Zeroization, and its honest limit
//!
//! Every secret in this crate lives in a `Zeroizing` wrapper or in an
//! `ed25519_dalek::SigningKey`, which is `ZeroizeOnDrop`. Intermediate hash
//! outputs and derivation preimages are wiped rather than dropped.
//!
//! **Under WASM this is best-effort and cannot be a guarantee.** The
//! specification already records why and this crate does not claim otherwise:
//! the JavaScript engine's garbage collector may have copied a buffer before
//! the Rust side overwrote the copy it can see, linear memory is not paged out
//! under the program's control, and a browser's own snapshotting is outside
//! anything a `Drop` impl reaches. Zeroization narrows the window; on wasm32 it
//! does not close it.
//!
//! # What this crate deliberately does not do
//!
//! No I/O, no clock, no randomness of its own, no network, no storage, no
//! policy, and **no signature verification** — `f2z-kt-core`'s `sig` module is
//! the workspace's one Ed25519 verifier and it is `verify_strict`. This crate
//! builds keys and signs with them. It also does not implement X-Wing: §3.1
//! decides that the hybrid KEM comes from OpenMLS's libcrux provider, so the
//! `DeviceInitKey` is generated by the MLS layer and reaches
//! [`credential::DeviceCredentialRequest`] as opaque public bytes. See
//! [`device`] for the full reasoning.
//!
//! # Changing a label or a personalization changes every user's identity
//!
//! Stated here as well as in [`labels`], because it is the one thing a reader
//! of this crate must not miss. The constants in [`labels`] are inputs to a
//! one-way derivation from a user's seed. Moving one byte moves every user's
//! `IdentitySigningKey`, invalidates every directory entry, breaks every pinned
//! safety number, and — because `KT.md` §4.4 requires the **outgoing** identity
//! key to sign a rotation — leaves no migration path that does not require the
//! old key. They have to be right now.
//!
//! # Deriving an identity and issuing a credential
//!
//! ```
//! use f2z_msg_identity::account::AccountKeys;
//! use f2z_msg_identity::credential::DeviceCredentialRequest;
//! use f2z_msg_identity::device::DeviceSignatureKey;
//! use f2z_kt_core::types::{Handle, KemPublicKey};
//!
//! # fn main() -> Result<(), Box<dyn core::error::Error>> {
//! # struct Rng(u64);
//! # impl rand_core::TryRng for Rng {
//! #     type Error = core::convert::Infallible;
//! #     fn try_next_u32(&mut self) -> Result<u32, Self::Error> { Ok(self.try_next_u64()? as u32) }
//! #     fn try_next_u64(&mut self) -> Result<u64, Self::Error> {
//! #         self.0 = self.0.wrapping_add(0x9e3779b97f4a7c15);
//! #         Ok(self.0)
//! #     }
//! #     fn try_fill_bytes(&mut self, dst: &mut [u8]) -> Result<(), Self::Error> {
//! #         for byte in dst.iter_mut() { *byte = self.try_next_u64()? as u8; }
//! #         Ok(())
//! #     }
//! # }
//! # impl rand_core::TryCryptoRng for Rng {}
//! # let mut os_rng = Rng(1);
//! // Restorable: the same mnemonic always yields the same identity.
//! let seed = [0x2a_u8; 64];
//! let account = AccountKeys::from_seed(&seed, 0)?;
//!
//! // Not restorable, and that is the point: straight from the OS CSPRNG.
//! let device = DeviceSignatureKey::generate(&mut os_rng);
//!
//! let credential = account.identity.issue_device_credential(&DeviceCredentialRequest {
//!     handle: Handle::new(b"alice".to_vec())?,
//!     device_pk: device.public(),
//!     // The MLS layer's X-Wing public key; opaque here (see `device`).
//!     device_kem_pk: KemPublicKey::new(vec![0xab; 1216])?,
//!     not_before_ms: 1_767_225_600_000,
//!     not_after_ms:  1_798_761_600_000,
//! })?;
//!
//! assert_eq!(credential.credential.identity_pk, account.identity.public());
//! # Ok(())
//! # }
//! ```
//!
//! [`docs/e2ee/ARCHITECTURE.md`]: https://github.com/free2z/zuu/blob/main/docs/e2ee/ARCHITECTURE.md
//! [ADR 0002]: https://github.com/free2z/zuu/blob/main/docs/e2ee/decisions/0002-multi-device.md
//! [ADR 0006]: https://github.com/free2z/zuu/blob/main/docs/e2ee/decisions/0006-zcash-coupling.md

#![no_std]
#![forbid(unsafe_code)]
#![cfg_attr(
    test,
    allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
        clippy::indexing_slicing,
        clippy::arithmetic_side_effects
    )
)]

extern crate alloc;

pub mod account;
pub mod blake;
pub mod credential;
pub mod device;
pub mod error;
pub mod labels;
pub mod node;

pub use account::{
    AccountKeys, BackupWrapKey, CeremonySigningKey, DirectoryAuthKey, IdentitySigningKey,
};
pub use credential::DeviceCredentialRequest;
pub use device::{DeviceKeys, DeviceSignatureKey, QueueKey};
pub use error::IdentityError;
pub use node::{
    COIN_TYPE, DEFAULT_ACCOUNT, ExtendedNode, HardenedIndex, PURPOSE, account_node, ckd_hardened,
    master_node,
};

/// The version of the messaging key hierarchy this crate implements.
///
/// It is not a wire field and nothing serializes it. It exists so that a change
/// to [`labels`]' constants — which changes every user's identity — has an
/// obvious, greppable companion that a reviewer will see move. There is no v2
/// and there is no migration story for one; see the crate note.
pub const MSG_IDENTITY_VERSION: u16 = 0x0001;
