//! **Identity is restorable from the mnemonic; device keys are not.**
//!
//! `ARCHITECTURE.md` §4.1, and [ADR 0002]'s reason for it: *"Device keys are
//! generated by the device's CSPRNG, never leave the device, and are not
//! derivable from the seed — so seed compromise does not retroactively yield
//! every device's MLS state."*
//!
//! The property has two halves and they pull in opposite directions, which is
//! why they are asserted together in one file:
//!
//! - **The identity half must be deterministic.** Restore the wallet, restore
//!   the identity. Same seed, same account index, same `IdentitySigningKey` —
//!   on any device, in any process, in any year. If this stopped holding, a
//!   user who restored a backup would find their handle no longer theirs.
//! - **The device half must not be.** Two devices restored from one mnemonic
//!   must be two devices. If a `DeviceSignatureKey` were seed-derived, then
//!   anyone who obtained the mnemonic — which the user is told to write on
//!   paper — could reconstruct every device's MLS leaf key, and MLS's forward
//!   secrecy would protect nothing against them.
//!
//! # What a test can and cannot prove here
//!
//! It cannot prove a *negative* about a whole API surface. What it can do is
//! demonstrate the observable consequence — device keys drawn from different
//! generator states differ — and record the structural argument, which is the
//! one that actually holds: [`DeviceSignatureKey`] and [`QueueKey`] have
//! exactly one constructor, `generate<R: CryptoRng>`, they hold their secret in
//! a private field, and nothing in this crate takes both a seed and returns
//! one. A `from_seed` on either would have to be *added*, and it would have to
//! be added to `device.rs`, whose module note says in the first paragraph why
//! it must not be.
//!
//! [ADR 0002]: https://github.com/free2z/zuu/blob/main/docs/e2ee/decisions/0002-multi-device.md

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use f2z_codec::types::PublicKey;
use f2z_msg_identity::account::AccountKeys;
use f2z_msg_identity::device::{DeviceSignatureKey, QueueKey};

const SEED: [u8; 64] = [0x2a; 64];

/// A counter, not a CSPRNG — see `device.rs`'s note on why `CryptoRng` is a
/// promise rather than a proof. Here it stands in for two *different* devices'
/// OS generators, which is what the seeds 1 and 2 mean below.
struct CountingRng(u64);

impl rand_core::TryRng for CountingRng {
    type Error = core::convert::Infallible;

    fn try_next_u32(&mut self) -> Result<u32, Self::Error> {
        Ok(self.try_next_u64()? as u32)
    }

    fn try_next_u64(&mut self) -> Result<u64, Self::Error> {
        self.0 = self.0.wrapping_add(0x9e37_79b9_7f4a_7c15);
        Ok(self.0)
    }

    fn try_fill_bytes(&mut self, dst: &mut [u8]) -> Result<(), Self::Error> {
        for byte in dst.iter_mut() {
            *byte = self.try_next_u64()? as u8;
        }
        Ok(())
    }
}

impl rand_core::TryCryptoRng for CountingRng {}

#[test]
fn the_identity_is_restorable_from_the_mnemonic() {
    // Two independent derivations, as two restores of the same backup would be.
    let first = AccountKeys::from_seed(&SEED, 0).unwrap();
    let second = AccountKeys::from_seed(&SEED, 0).unwrap();

    assert_eq!(first.identity.public(), second.identity.public());
    assert_eq!(first.ceremony.public(), second.ceremony.public());
    assert_eq!(
        first.directory_auth.public(),
        second.directory_auth.public()
    );
    assert_eq!(first.backup_wrap.as_bytes(), second.backup_wrap.as_bytes());
}

#[test]
fn two_devices_restored_from_one_mnemonic_are_two_devices() {
    // The same account, on two devices whose OS generators are — as they are in
    // reality — unrelated.
    let account = AccountKeys::from_seed(&SEED, 0).unwrap();
    let phone = DeviceSignatureKey::generate(&mut CountingRng(1));
    let laptop = DeviceSignatureKey::generate(&mut CountingRng(2));

    assert_ne!(
        phone.public(),
        laptop.public(),
        "two devices of one account share a leaf signature key; ADR 0002's \
         per-device fan-out is not per-device"
    );

    // And neither is anywhere in the seed-derived half.
    let seed_derived: [PublicKey; 3] = [
        account.identity.public(),
        account.ceremony.public(),
        account.directory_auth.public(),
    ];
    for device in [phone.public(), laptop.public()] {
        for identity in &seed_derived {
            assert_ne!(&device, identity, "a device key equals a seed-derived key");
        }
        assert_ne!(
            device.as_bytes(),
            account.backup_wrap.as_bytes(),
            "a device key equals the backup wrap key"
        );
    }
}

#[test]
fn queue_keys_are_not_seed_derived_either() {
    // `QueueKey_{q}` is in the same table for the same reason: a relay sees it,
    // and a queue key reconstructible from a mnemonic would let anyone holding
    // the mnemonic impersonate the user to a relay.
    let account = AccountKeys::from_seed(&SEED, 0).unwrap();
    let a = QueueKey::generate(&mut CountingRng(11));
    let b = QueueKey::generate(&mut CountingRng(12));
    assert_ne!(a.public(), b.public());
    assert_ne!(a.public(), account.identity.public());
}

#[test]
fn the_generator_is_the_only_source_of_a_device_key() {
    // The observable form of the structural argument in the module note: a
    // device key is a pure function of the generator's output and of nothing
    // else — not of the seed, which is not even an argument. Two calls against
    // generators in the same state agree; that is what makes the previous test
    // a statement about the generators rather than about luck.
    let a = DeviceSignatureKey::generate(&mut CountingRng(5));
    let b = DeviceSignatureKey::generate(&mut CountingRng(5));
    assert_eq!(a.public(), b.public());
}
