/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const otpDisableDestroy = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/otp/disable/`, method: 'DELETE'
    },
      options);
    }
  


export const getOtpDisableDestroyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof otpDisableDestroy>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof otpDisableDestroy>>, TError,void, TContext> => {

const mutationKey = ['otpDisableDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof otpDisableDestroy>>, void> = () => {
          

          return  otpDisableDestroy(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OtpDisableDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof otpDisableDestroy>>>
    
    export type OtpDisableDestroyMutationError = unknown

    export const createOtpDisableDestroy = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof otpDisableDestroy>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof otpDisableDestroy>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getOtpDisableDestroyMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const otpEnableCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/otp/enable/`, method: 'POST', signal
    },
      options);
    }
  


export const getOtpEnableCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof otpEnableCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof otpEnableCreate>>, TError,void, TContext> => {

const mutationKey = ['otpEnableCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof otpEnableCreate>>, void> = () => {
          

          return  otpEnableCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OtpEnableCreateMutationResult = NonNullable<Awaited<ReturnType<typeof otpEnableCreate>>>
    
    export type OtpEnableCreateMutationError = unknown

    export const createOtpEnableCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof otpEnableCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof otpEnableCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getOtpEnableCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const otpLoginCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/otp/login/`, method: 'POST', signal
    },
      options);
    }
  


export const getOtpLoginCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof otpLoginCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof otpLoginCreate>>, TError,void, TContext> => {

const mutationKey = ['otpLoginCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof otpLoginCreate>>, void> = () => {
          

          return  otpLoginCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OtpLoginCreateMutationResult = NonNullable<Awaited<ReturnType<typeof otpLoginCreate>>>
    
    export type OtpLoginCreateMutationError = unknown

    export const createOtpLoginCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof otpLoginCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof otpLoginCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getOtpLoginCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const otpSetupCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/otp/setup/`, method: 'POST', signal
    },
      options);
    }
  


export const getOtpSetupCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof otpSetupCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof otpSetupCreate>>, TError,void, TContext> => {

const mutationKey = ['otpSetupCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof otpSetupCreate>>, void> = () => {
          

          return  otpSetupCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OtpSetupCreateMutationResult = NonNullable<Awaited<ReturnType<typeof otpSetupCreate>>>
    
    export type OtpSetupCreateMutationError = unknown

    export const createOtpSetupCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof otpSetupCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof otpSetupCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getOtpSetupCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const otpStatusRetrieve = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/otp/status/`, method: 'GET', signal
    },
      options);
    }
  



export const getOtpStatusRetrieveQueryKey = () => {
    return [
    `/api/otp/status/`
    ] as const;
    }

    
export const getOtpStatusRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof otpStatusRetrieve>>, TError = unknown>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof otpStatusRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOtpStatusRetrieveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof otpStatusRetrieve>>> = ({ signal }) => otpStatusRetrieve(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof otpStatusRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type OtpStatusRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof otpStatusRetrieve>>>
export type OtpStatusRetrieveQueryError = unknown



export function createOtpStatusRetrieve<TData = Awaited<ReturnType<typeof otpStatusRetrieve>>, TError = unknown>(
  options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof otpStatusRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getOtpStatusRetrieveQueryOptions(options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




