/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  PaginatedStoryFullList,
  PatchedStoryFull,
  StoryFull,
  StorytimeMystoriesListParams
} from '../f2z.schemas';

import { customInstance } from '.././mutator';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const storytimeRetrieve = (
    creator: string,
    slug: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/storytime/${creator}/${slug}`, method: 'GET', signal
    },
      options);
    }
  



export const getStorytimeRetrieveQueryKey = (creator?: string,
    slug?: string,) => {
    return [
    `/api/storytime/${creator}/${slug}`
    ] as const;
    }

    
export const getStorytimeRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof storytimeRetrieve>>, TError = unknown>(creator: string,
    slug: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof storytimeRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStorytimeRetrieveQueryKey(creator,slug);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storytimeRetrieve>>> = ({ signal }) => storytimeRetrieve(creator,slug, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(creator && slug), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof storytimeRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type StorytimeRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof storytimeRetrieve>>>
export type StorytimeRetrieveQueryError = unknown



export function createStorytimeRetrieve<TData = Awaited<ReturnType<typeof storytimeRetrieve>>, TError = unknown>(
 creator: string,
    slug: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof storytimeRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getStorytimeRetrieveQueryOptions(creator,slug,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const storytimeImageCreate = (
    slug: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/storytime/${slug}/image`, method: 'POST', signal
    },
      options);
    }
  


export const getStorytimeImageCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof storytimeImageCreate>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof storytimeImageCreate>>, TError,{slug: string}, TContext> => {

const mutationKey = ['storytimeImageCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storytimeImageCreate>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  storytimeImageCreate(slug,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StorytimeImageCreateMutationResult = NonNullable<Awaited<ReturnType<typeof storytimeImageCreate>>>
    
    export type StorytimeImageCreateMutationError = unknown

    export const createStorytimeImageCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof storytimeImageCreate>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof storytimeImageCreate>>,
        TError,
        {slug: string},
        TContext
      > => {

      const mutationOptions = getStorytimeImageCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const storytimeTextCreate = (
    slug: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/storytime/${slug}/text`, method: 'POST', signal
    },
      options);
    }
  


export const getStorytimeTextCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof storytimeTextCreate>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof storytimeTextCreate>>, TError,{slug: string}, TContext> => {

const mutationKey = ['storytimeTextCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storytimeTextCreate>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  storytimeTextCreate(slug,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StorytimeTextCreateMutationResult = NonNullable<Awaited<ReturnType<typeof storytimeTextCreate>>>
    
    export type StorytimeTextCreateMutationError = unknown

    export const createStorytimeTextCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof storytimeTextCreate>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof storytimeTextCreate>>,
        TError,
        {slug: string},
        TContext
      > => {

      const mutationOptions = getStorytimeTextCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    /**
 * Use this for own stories
 */
export const storytimeMystoriesList = (
    params?: StorytimeMystoriesListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedStoryFullList>(
      {url: `/api/storytime/mystories/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getStorytimeMystoriesListQueryKey = (params?: StorytimeMystoriesListParams,) => {
    return [
    `/api/storytime/mystories/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStorytimeMystoriesListQueryOptions = <TData = Awaited<ReturnType<typeof storytimeMystoriesList>>, TError = unknown>(params?: StorytimeMystoriesListParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof storytimeMystoriesList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStorytimeMystoriesListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storytimeMystoriesList>>> = ({ signal }) => storytimeMystoriesList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof storytimeMystoriesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type StorytimeMystoriesListQueryResult = NonNullable<Awaited<ReturnType<typeof storytimeMystoriesList>>>
export type StorytimeMystoriesListQueryError = unknown



export function createStorytimeMystoriesList<TData = Awaited<ReturnType<typeof storytimeMystoriesList>>, TError = unknown>(
 params?: StorytimeMystoriesListParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof storytimeMystoriesList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getStorytimeMystoriesListQueryOptions(params,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Use this for own stories
 */
export const storytimeMystoriesRetrieve = (
    slug: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StoryFull>(
      {url: `/api/storytime/mystories/${slug}`, method: 'GET', signal
    },
      options);
    }
  



export const getStorytimeMystoriesRetrieveQueryKey = (slug?: string,) => {
    return [
    `/api/storytime/mystories/${slug}`
    ] as const;
    }

    
export const getStorytimeMystoriesRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof storytimeMystoriesRetrieve>>, TError = unknown>(slug: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof storytimeMystoriesRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStorytimeMystoriesRetrieveQueryKey(slug);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storytimeMystoriesRetrieve>>> = ({ signal }) => storytimeMystoriesRetrieve(slug, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(slug), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof storytimeMystoriesRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type StorytimeMystoriesRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof storytimeMystoriesRetrieve>>>
export type StorytimeMystoriesRetrieveQueryError = unknown



export function createStorytimeMystoriesRetrieve<TData = Awaited<ReturnType<typeof storytimeMystoriesRetrieve>>, TError = unknown>(
 slug: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof storytimeMystoriesRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getStorytimeMystoriesRetrieveQueryOptions(slug,options)

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Use this for own stories
 */
export const storytimeMystoriesPartialUpdate = (
    slug: string,
    patchedStoryFull: NonReadonly<PatchedStoryFull>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<StoryFull>(
      {url: `/api/storytime/mystories/${slug}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedStoryFull
    },
      options);
    }
  


export const getStorytimeMystoriesPartialUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof storytimeMystoriesPartialUpdate>>, TError,{slug: string;data: NonReadonly<PatchedStoryFull>}, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof storytimeMystoriesPartialUpdate>>, TError,{slug: string;data: NonReadonly<PatchedStoryFull>}, TContext> => {

const mutationKey = ['storytimeMystoriesPartialUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storytimeMystoriesPartialUpdate>>, {slug: string;data: NonReadonly<PatchedStoryFull>}> = (props) => {
          const {slug,data} = props ?? {};

          return  storytimeMystoriesPartialUpdate(slug,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StorytimeMystoriesPartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof storytimeMystoriesPartialUpdate>>>
    export type StorytimeMystoriesPartialUpdateMutationBody = NonReadonly<PatchedStoryFull>
    export type StorytimeMystoriesPartialUpdateMutationError = unknown

    export const createStorytimeMystoriesPartialUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof storytimeMystoriesPartialUpdate>>, TError,{slug: string;data: NonReadonly<PatchedStoryFull>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof storytimeMystoriesPartialUpdate>>,
        TError,
        {slug: string;data: NonReadonly<PatchedStoryFull>},
        TContext
      > => {

      const mutationOptions = getStorytimeMystoriesPartialUpdateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const storytimeStartCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/storytime/start`, method: 'POST', signal
    },
      options);
    }
  


export const getStorytimeStartCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof storytimeStartCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof storytimeStartCreate>>, TError,void, TContext> => {

const mutationKey = ['storytimeStartCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof storytimeStartCreate>>, void> = () => {
          

          return  storytimeStartCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StorytimeStartCreateMutationResult = NonNullable<Awaited<ReturnType<typeof storytimeStartCreate>>>
    
    export type StorytimeStartCreateMutationError = unknown

    export const createStorytimeStartCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof storytimeStartCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof storytimeStartCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getStorytimeStartCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    