/**
 * Generated by orval 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import { createMutation, createQuery } from "@tanstack/svelte-query";
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
} from "@tanstack/svelte-query";

import type {
  PaginatedStoryFullList,
  PatchedStoryFull,
  StoryFull,
  StorytimeMystoriesListParams,
} from "../f2z.schemas";

import { customInstance } from ".././mutator";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getStorytimeRetrieveUrl = (creator: string, slug: string) => {
  return `/api/storytime/${creator}/${slug}`;
};

export const storytimeRetrieve = async (
  creator: string,
  slug: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getStorytimeRetrieveUrl(creator, slug), {
    ...options,
    method: "GET",
  });
};

export const getStorytimeRetrieveQueryKey = (creator: string, slug: string) => {
  return [`/api/storytime/${creator}/${slug}`] as const;
};

export const getStorytimeRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof storytimeRetrieve>>,
  TError = unknown,
>(
  creator: string,
  slug: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof storytimeRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getStorytimeRetrieveQueryKey(creator, slug);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof storytimeRetrieve>>
  > = ({ signal }) =>
    storytimeRetrieve(creator, slug, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled:
      creator !== null &&
      creator !== undefined &&
      slug !== null &&
      slug !== undefined,
    ...queryOptions,
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof storytimeRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StorytimeRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof storytimeRetrieve>>
>;
export type StorytimeRetrieveQueryError = unknown;

export function createStorytimeRetrieve<
  TData = Awaited<ReturnType<typeof storytimeRetrieve>>,
  TError = unknown,
>(
  creator: string,
  slug: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof storytimeRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStorytimeRetrieveQueryOptions(creator, slug, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getStorytimeImageCreateUrl = (slug: string) => {
  return `/api/storytime/${slug}/image`;
};

export const storytimeImageCreate = async (
  slug: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getStorytimeImageCreateUrl(slug), {
    ...options,
    method: "POST",
  });
};

export const getStorytimeImageCreateMutationKey = () =>
  ["storytimeImageCreate"] as const;

export const getStorytimeImageCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof storytimeImageCreate>>,
    TError,
    StorytimeImageCreateMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof storytimeImageCreate>>,
  TError,
  StorytimeImageCreateMutationVariables,
  TContext
> => {
  const mutationKey = getStorytimeImageCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storytimeImageCreate>>,
    StorytimeImageCreateMutationVariables
  > = (props) => {
    const { slug } = props ?? {};

    return storytimeImageCreate(slug, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorytimeImageCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof storytimeImageCreate>>
>;

export type StorytimeImageCreateMutationError = unknown;
export type StorytimeImageCreateMutationVariables = { slug: string };

export const createStorytimeImageCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof storytimeImageCreate>>,
      TError,
      StorytimeImageCreateMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof storytimeImageCreate>>,
  TError,
  StorytimeImageCreateMutationVariables,
  TContext
> => {
  return createMutation(getStorytimeImageCreateMutationOptions(options));
};
export const getStorytimeTextCreateUrl = (slug: string) => {
  return `/api/storytime/${slug}/text`;
};

export const storytimeTextCreate = async (
  slug: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getStorytimeTextCreateUrl(slug), {
    ...options,
    method: "POST",
  });
};

export const getStorytimeTextCreateMutationKey = () =>
  ["storytimeTextCreate"] as const;

export const getStorytimeTextCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof storytimeTextCreate>>,
    TError,
    StorytimeTextCreateMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof storytimeTextCreate>>,
  TError,
  StorytimeTextCreateMutationVariables,
  TContext
> => {
  const mutationKey = getStorytimeTextCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storytimeTextCreate>>,
    StorytimeTextCreateMutationVariables
  > = (props) => {
    const { slug } = props ?? {};

    return storytimeTextCreate(slug, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorytimeTextCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof storytimeTextCreate>>
>;

export type StorytimeTextCreateMutationError = unknown;
export type StorytimeTextCreateMutationVariables = { slug: string };

export const createStorytimeTextCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof storytimeTextCreate>>,
      TError,
      StorytimeTextCreateMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof storytimeTextCreate>>,
  TError,
  StorytimeTextCreateMutationVariables,
  TContext
> => {
  return createMutation(getStorytimeTextCreateMutationOptions(options));
};
export const getStorytimeMystoriesListUrl = (
  params?: StorytimeMystoriesListParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/storytime/mystories/?${stringifiedParams}`
    : `/api/storytime/mystories/`;
};

/**
 * Use this for own stories
 */
export const storytimeMystoriesList = async (
  params?: StorytimeMystoriesListParams,
  options?: Parameters<typeof customInstance>[1],
): Promise<PaginatedStoryFullList> => {
  return customInstance<PaginatedStoryFullList>(
    getStorytimeMystoriesListUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getStorytimeMystoriesListQueryKey = (
  params?: StorytimeMystoriesListParams,
) => {
  return [`/api/storytime/mystories/`, ...(params ? [params] : [])] as const;
};

export const getStorytimeMystoriesListQueryOptions = <
  TData = Awaited<ReturnType<typeof storytimeMystoriesList>>,
  TError = unknown,
>(
  params?: StorytimeMystoriesListParams,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof storytimeMystoriesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getStorytimeMystoriesListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof storytimeMystoriesList>>
  > = ({ signal }) =>
    storytimeMystoriesList(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof storytimeMystoriesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StorytimeMystoriesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof storytimeMystoriesList>>
>;
export type StorytimeMystoriesListQueryError = unknown;

export function createStorytimeMystoriesList<
  TData = Awaited<ReturnType<typeof storytimeMystoriesList>>,
  TError = unknown,
>(
  params?: StorytimeMystoriesListParams,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof storytimeMystoriesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStorytimeMystoriesListQueryOptions(params, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getStorytimeMystoriesRetrieveUrl = (slug: string) => {
  return `/api/storytime/mystories/${slug}`;
};

/**
 * Use this for own stories
 */
export const storytimeMystoriesRetrieve = async (
  slug: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<StoryFull> => {
  return customInstance<StoryFull>(getStorytimeMystoriesRetrieveUrl(slug), {
    ...options,
    method: "GET",
  });
};

export const getStorytimeMystoriesRetrieveQueryKey = (slug: string) => {
  return [`/api/storytime/mystories/${slug}`] as const;
};

export const getStorytimeMystoriesRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof storytimeMystoriesRetrieve>>,
  TError = unknown,
>(
  slug: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof storytimeMystoriesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getStorytimeMystoriesRetrieveQueryKey(slug);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof storytimeMystoriesRetrieve>>
  > = ({ signal }) =>
    storytimeMystoriesRetrieve(slug, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: slug !== null && slug !== undefined,
    ...queryOptions,
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof storytimeMystoriesRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StorytimeMystoriesRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof storytimeMystoriesRetrieve>>
>;
export type StorytimeMystoriesRetrieveQueryError = unknown;

export function createStorytimeMystoriesRetrieve<
  TData = Awaited<ReturnType<typeof storytimeMystoriesRetrieve>>,
  TError = unknown,
>(
  slug: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof storytimeMystoriesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getStorytimeMystoriesRetrieveQueryOptions(slug, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getStorytimeMystoriesPartialUpdateUrl = (slug: string) => {
  return `/api/storytime/mystories/${slug}`;
};

/**
 * Use this for own stories
 */
export const storytimeMystoriesPartialUpdate = async (
  slug: string,
  patchedStoryFull?: NonReadonly<PatchedStoryFull>,
  options?: Parameters<typeof customInstance>[1],
): Promise<StoryFull> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return customInstance<StoryFull>(
    getStorytimeMystoriesPartialUpdateUrl(slug),
    {
      ...options,
      method: "PATCH",
      headers: {
        "Content-Type": "application/json",
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(patchedStoryFull),
    },
  );
};

export const getStorytimeMystoriesPartialUpdateMutationKey = () =>
  ["storytimeMystoriesPartialUpdate"] as const;

export const getStorytimeMystoriesPartialUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof storytimeMystoriesPartialUpdate>>,
    TError,
    StorytimeMystoriesPartialUpdateMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof storytimeMystoriesPartialUpdate>>,
  TError,
  StorytimeMystoriesPartialUpdateMutationVariables,
  TContext
> => {
  const mutationKey = getStorytimeMystoriesPartialUpdateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storytimeMystoriesPartialUpdate>>,
    StorytimeMystoriesPartialUpdateMutationVariables
  > = (props) => {
    const { slug, data } = props ?? {};

    return storytimeMystoriesPartialUpdate(slug, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorytimeMystoriesPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof storytimeMystoriesPartialUpdate>>
>;
export type StorytimeMystoriesPartialUpdateMutationBody =
  NonReadonly<PatchedStoryFull> | undefined;
export type StorytimeMystoriesPartialUpdateMutationError = unknown;
export type StorytimeMystoriesPartialUpdateMutationVariables = {
  slug: string;
  data?: NonReadonly<PatchedStoryFull>;
};

export const createStorytimeMystoriesPartialUpdate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof storytimeMystoriesPartialUpdate>>,
      TError,
      StorytimeMystoriesPartialUpdateMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof storytimeMystoriesPartialUpdate>>,
  TError,
  StorytimeMystoriesPartialUpdateMutationVariables,
  TContext
> => {
  return createMutation(
    getStorytimeMystoriesPartialUpdateMutationOptions(options),
  );
};
export const getStorytimeStartCreateUrl = () => {
  return `/api/storytime/start`;
};

export const storytimeStartCreate = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getStorytimeStartCreateUrl(), {
    ...options,
    method: "POST",
  });
};

export const getStorytimeStartCreateMutationKey = () =>
  ["storytimeStartCreate"] as const;

export const getStorytimeStartCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof storytimeStartCreate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof storytimeStartCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getStorytimeStartCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof storytimeStartCreate>>,
    void
  > = () => {
    return storytimeStartCreate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StorytimeStartCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof storytimeStartCreate>>
>;

export type StorytimeStartCreateMutationError = unknown;

export const createStorytimeStartCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof storytimeStartCreate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof storytimeStartCreate>>,
  TError,
  void,
  TContext
> => {
  return createMutation(getStorytimeStartCreateMutationOptions(options));
};
