/**
 * Generated by orval 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import { createMutation } from "@tanstack/svelte-query";
import type {
  CreateMutationOptions,
  CreateMutationResult,
  MutationFunction,
  QueryClient,
} from "@tanstack/svelte-query";

import { customInstance } from ".././mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getTokenLoginCreateUrl = () => {
  return `/api/token/login/`;
};

export const tokenLoginCreate = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getTokenLoginCreateUrl(), {
    ...options,
    method: "POST",
  });
};

export const getTokenLoginCreateMutationKey = () =>
  ["tokenLoginCreate"] as const;

export const getTokenLoginCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof tokenLoginCreate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof tokenLoginCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getTokenLoginCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tokenLoginCreate>>,
    void
  > = () => {
    return tokenLoginCreate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TokenLoginCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tokenLoginCreate>>
>;

export type TokenLoginCreateMutationError = unknown;

export const createTokenLoginCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof tokenLoginCreate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof tokenLoginCreate>>,
  TError,
  void,
  TContext
> => {
  return createMutation(getTokenLoginCreateMutationOptions(options));
};
export const getTokenLogoutCreateUrl = () => {
  return `/api/token/logout/`;
};

export const tokenLogoutCreate = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getTokenLogoutCreateUrl(), {
    ...options,
    method: "POST",
  });
};

export const getTokenLogoutCreateMutationKey = () =>
  ["tokenLogoutCreate"] as const;

export const getTokenLogoutCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof tokenLogoutCreate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof tokenLogoutCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getTokenLogoutCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tokenLogoutCreate>>,
    void
  > = () => {
    return tokenLogoutCreate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TokenLogoutCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tokenLogoutCreate>>
>;

export type TokenLogoutCreateMutationError = unknown;

export const createTokenLogoutCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof tokenLogoutCreate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof tokenLogoutCreate>>,
  TError,
  void,
  TContext
> => {
  return createMutation(getTokenLogoutCreateMutationOptions(options));
};
export const getTokenLogoutallCreateUrl = () => {
  return `/api/token/logoutall/`;
};

/**
 * Log the user out of all sessions
 * I.E. deletes all auth tokens for the user
 */
export const tokenLogoutallCreate = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getTokenLogoutallCreateUrl(), {
    ...options,
    method: "POST",
  });
};

export const getTokenLogoutallCreateMutationKey = () =>
  ["tokenLogoutallCreate"] as const;

export const getTokenLogoutallCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof tokenLogoutallCreate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof tokenLogoutallCreate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getTokenLogoutallCreateMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tokenLogoutallCreate>>,
    void
  > = () => {
    return tokenLogoutallCreate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TokenLogoutallCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tokenLogoutallCreate>>
>;

export type TokenLogoutallCreateMutationError = unknown;

export const createTokenLogoutallCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof tokenLogoutallCreate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): CreateMutationResult<
  Awaited<ReturnType<typeof tokenLogoutallCreate>>,
  TError,
  void,
  TContext
> => {
  return createMutation(getTokenLogoutallCreateMutationOptions(options));
};
