/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * f2z
 * Free2z is a tool for content and peer-2-peer giving that does not compromise on privacy
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  MutationFunction,
  QueryClient
} from '@tanstack/svelte-query';

import { customInstance } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const tokenLoginCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/token/login/`, method: 'POST', signal
    },
      options);
    }
  


export const getTokenLoginCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof tokenLoginCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof tokenLoginCreate>>, TError,void, TContext> => {

const mutationKey = ['tokenLoginCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tokenLoginCreate>>, void> = () => {
          

          return  tokenLoginCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TokenLoginCreateMutationResult = NonNullable<Awaited<ReturnType<typeof tokenLoginCreate>>>
    
    export type TokenLoginCreateMutationError = unknown

    export const createTokenLoginCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof tokenLoginCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof tokenLoginCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getTokenLoginCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    export const tokenLogoutCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/token/logout/`, method: 'POST', signal
    },
      options);
    }
  


export const getTokenLogoutCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof tokenLogoutCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof tokenLogoutCreate>>, TError,void, TContext> => {

const mutationKey = ['tokenLogoutCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tokenLogoutCreate>>, void> = () => {
          

          return  tokenLogoutCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TokenLogoutCreateMutationResult = NonNullable<Awaited<ReturnType<typeof tokenLogoutCreate>>>
    
    export type TokenLogoutCreateMutationError = unknown

    export const createTokenLogoutCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof tokenLogoutCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof tokenLogoutCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getTokenLogoutCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    /**
 * Log the user out of all sessions
I.E. deletes all auth tokens for the user
 */
export const tokenLogoutallCreate = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/token/logoutall/`, method: 'POST', signal
    },
      options);
    }
  


export const getTokenLogoutallCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof tokenLogoutallCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): CreateMutationOptions<Awaited<ReturnType<typeof tokenLogoutallCreate>>, TError,void, TContext> => {

const mutationKey = ['tokenLogoutallCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tokenLogoutallCreate>>, void> = () => {
          

          return  tokenLogoutallCreate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TokenLogoutallCreateMutationResult = NonNullable<Awaited<ReturnType<typeof tokenLogoutallCreate>>>
    
    export type TokenLogoutallCreateMutationError = unknown

    export const createTokenLogoutallCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof tokenLogoutallCreate>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof tokenLogoutallCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getTokenLogoutallCreateMutationOptions(options);

      return createMutation(mutationOptions, queryClient);
    }
    